GoogleChrome/webstatus.dev

frontend/src/static/index.html
This is the solution recommended here:
https://stackoverflow.com/questions/23367345/100vw-causing-horizontal-overflow-but-only-if-more-than-one
=> Avoid horizontal scrollbar on safari.

infra/.envs/prod.tfvars, infra/.envs/staging.tfvars, infra/ingestion/variables.tf, infra/ingestion/workflows.tf, infra/ingestion/workflows/bcd/main.tf, infra/ingestion/workflows/bcd/variables.tf, infra/ingestion/workflows/web_features_repo/main.tf, infra/ingestion/workflows/web_features_repo/variables.tf, infra/ingestion/workflows/wpt/main.tf, infra/ingestion/workflows/wpt/variables.tf, infra/main.tf, infra/variables.tf
Previously, I ran the workflows myself whenever needed. But we should not rely on that long term.
This change puts a cron schedule on the various workflows.
We run them in order
- bcd (contains the browser info)
- web features (features info that uses some of the browser info from bcd)
- wpt (scores that maps to web features)
The workflows are deployed many regions so we just add a cron for each of those regions.
=> Add the cron schedule for the ingestion pipelines

frontend/src/static/js/components/test/webstatus-feature-page.test.ts, frontend/src/static/js/components/webstatus-feature-page.ts
We currently link to the stable wpt.fyi page in wpt.fyi everytime. Even if the feature does not have wpt.fyi stable tests.
This change hides the wpt.fyi link if there are no stable metrics for that feature.
Fixes #296
=> Only show wpt.fyi link if there are stable metrics

e2e/tests/feature-page.spec.ts, frontend/src/static/js/components/webstatus-feature-page.ts
This is a fix for #279.  The VaadinRouter handles clicks on all links by default, and for links within pages (that have the same base URL) it assumes the page will update itself.  But we can simply add the 'router-ignore' attribute to the anchor tag to have the router ignore the link and thus behave as it normally would.
=> Fix feature link to update page

frontend/src/static/js/components/webstatus-feature-page.ts, frontend/src/static/js/components/webstatus-gchart.ts
Disabling the multi-selection mode fixes the problem of accumulating data points in the tooltip without an easy way of clearing the selection, in #309.
Google Charts has no support for control-click, which would be the appropriate way to allow multi-selection as a modifier of normal clicking.   A fairly complex workaround would involve handling mouse events at the chart container level outside the chart, and converting those event into modifications of the selection in the chart by determining what data point was selected.  Alternatively, we could support clicking in the chart area but not on any data point in order to clear the selection.
=> Move the multi-selection option to gchart, and disable.

.github/workflows/ci.yml, .github/workflows/devcontainer.yml, Makefile
This is the beginning of the work described in https://github.com/GoogleChrome/webstatus.dev/issues/329
It will cover the first two check boxes on that issue.
This change creates a new GitHub CI workflow that will refresh the images:
- Every tuesday (the dependabot notices will be configured for Monday)
- Ad-hoc runs that can be triggered on the Actions page
Two of the images are now used in the existing build GitHub action.
We have to split them up because the GitHub runner runs out of space. We could clean up more and try to fit it all into one image but that can come in the future.
For now, this should reduce the time spent in Github Action machine hours.
The playwright image is not caching the docker images built in `skaffold-build` but we can fix that in the future too.
=> Create reusable base devcontainer images

.github/workflows/ci.yml, .github/workflows/devcontainer.yml, DEVELOPMENT.md, Makefile, docs/testing.md, e2e/tests/overview-page.spec.ts
Following https://playwright.dev/docs/ci-intro#viewing-the-trace
Add a command to list the github runs
- ![image](https://github.com/GoogleChrome/webstatus.dev/assets/7788930/73b463cc-a6ae-465d-9a95-cb3c6b42ab9b)
Add a command to download the playwright report from a given GitHub run
Add instructions on opening report
- ![image](https://github.com/GoogleChrome/webstatus.dev/assets/7788930/672ff6b3-6316-4461-b30b-9e3db035eedb)
Add instructions on opening a playwright trace
- ![image](https://github.com/GoogleChrome/webstatus.dev/assets/7788930/c9036ba9-521a-4997-9633-915c633406d3)
Other changes:
- Call `make build` before running the playwright tests
- Start to fill in documentation for testing
=> Upload playwright report, helper scripts to download

e2e/tests/nginx-conf.spec.ts, e2e/tests/overview-page.spec.ts, e2e/tests/utils.ts, frontend/nginx.conf, playwright.config.ts
As reported in #367, the gzip compression is not working for the static resources.
This change fixes that by enabling gzip:
- For the static resources in the public directory
- The index.html that is served
Added a test make sure Content-Encoding is indeed coming back from the NGINX server.
=> Fix gzip compression

e2e/tests/index-html.spec.ts, frontend/src/static/index.html
Add playwright test that checks for the preconnect links on the page.
fetch is currently configured to send credentials (because of UbP). We need to configure this preconnect to also send credentials as well.
Fixes #384
=> Add preconnect for api.

Makefile
@dlaliberte and @past  both recently posted about this.
This makes it so that we run make build before running dev_workflow and dev_fake_data
Fixes #426
=> Mark `build` as a pre-req for dev_workflow and dev_fake_data

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
This follows the instructions [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) to get default templates. The only modifications I made to the default templates were:
- Add appropriate labels 
- Title placeholder
- Running make lint-fix to fix formatting
=> Add default issue templates

frontend/src/static/js/components/test/webstatus-typeahead.test.ts, frontend/src/static/js/components/webstatus-typeahead.ts
This should resolve #260.  Now, `webstatus-typeahead` keeps track of whether the last action was selecting a completion, and in that case the menu is not shown.
Also, since we added support for dates that are formatted like `2024-06-28`, I made `findPrefix()` smarter about dashes used as negation operators vs. dashes that occur within a term.
=> Keep typeahead closed after selection

infra/backend/service.tf
This should hopefully address #269
The default number of retries is 3. This has been adjusted to 10.
The default number of seconds it waits before timing out is 1 second. That has been adjusted to 10 seconds.
=> Adjust liveness probe for opentelemetry

package-lock.json
The command I ran to generate this change: `npm audit fix`
Turns out there is a vuln in the `ip` package.
We don't use it directly. But web-test-runner does
web-test-runner changed from using ip to another package completely. This change just bumps the version of web-test-runner (which then uses the version without ip)
=> chore: Fix dependabot alert for CVE-2023-42282

.dev/datastore/manifests/pod.yaml, .dev/gcs/manifests/pod.yaml, .dev/redis/manifests/pod.yaml, .dev/spanner/manifests/pod.yaml, backend/manifests/pod.yaml, frontend/manifests/pod.yaml, workflows/steps/services/common/repo_downloader/manifests/pod.yaml, workflows/steps/services/web_feature_consumer/manifests/pod.yaml
Sometimes, a developer can run into issues like this:
```
Watching for changes...
Error response from daemon: pull access denied for web-feature-consumer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Back-off pulling image "web-feature-consumer:121b121c17ed07dc780afd3f7152621a8cba2bfaaf2e008f9d97a4d2f176adc3"
```
This is because minikube is trying to pull the image from docker hub. In reality, this should never happen because the image is built locally.
By setting [imagePullPolicy](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy) to never, we are forcing the cluster to look locally for the image.
This was done for some resources but not all. This change should fix all the outstanding services.
=> Set imagePullPolicy to never for locally built images

otel/otel-collector-config.yaml
Opentelemetry was recently updated in #476
I did not read the Changelog but there's an important notice there from the release [notes](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.104.0):
> Expansion of BASH-style environment variables, such as $FOO is no longer supported by default. If you depend on this syntax, disable the confmap.unifyEnvVarExpansion feature gate, but know that the feature will be removed in the future in favor of ${env:FOO}.
I started to see problems in staging when I deployed it.
This change fixes it to be consistent with other environment variables.
=> Fix opentelemetry config

workflows/steps/services/wpt_consumer/pkg/workflow/wpt_run_processor.go, workflows/steps/services/wpt_consumer/pkg/workflow/wpt_run_processor_test.go
WPT has two file formats: v1 and v2.
V1 does not have enough information. So we can skip those completely.
This change does that.
=> Only process v2 WPT files

infra/storage/spanner/migrations/000005.sql, lib/gcpspanner/feature_base_query.go, lib/gcpspanner/wpt_run_feature_metric.go, lib/gcpspanner/wpt_run_feature_metric_test.go
Finding the latest metric before an arbitrary timestamp is complex because Spanner does not currently support SQL window functions like RANK or ROW_NUMBER. These would be ideal for directly identifying the latest metric for a given timestamp within a query. To compensate for that, there are multiple subqueries to:
1. find the latest wpt metric for a feature given a certain browser name + channel combo and
2. build the struct.
This initial design allowed for flexible time-based filtering to retrieve data at arbitrary timestamps but we don't need that functionality. (Tradeoff: This would have allowed users to share the view of what one user saw exactly at a given timestamp)
Fixes #382
Other things tried:
- I tried to get rid of the emulator specific queries but they didn't seem to get …
=> Add LatestWPTRunFeatureMetrics table to speed up initial look ups

e2e/tests/nginx-conf.spec.ts, frontend/nginx.conf
I fixed GZIP compression. However, when I deployed it to GCP, it still did not work. Turns out that nginx turns off gzip compression when there's a Via header sent. (which is what GCP load balancers do) [1]
This change follows the recommendations from the GCP docs [1] and modifies the test to use a Via header to simulate being in a GCP environment to be close to what is used live.
[1] https://cloud.google.com/load-balancing/docs/https/troubleshooting-ext-https-lbs#compression-not-working
Via value seen in browser
=> Fix gzip compression in GCP

DEPLOYMENT.md, infra/backend/service.tf, infra/frontend/service.tf, infra/ingestion/common_workflow_steps/repo_downloader/main.tf, infra/ingestion/workflows/web_features_repo/web_feature_service.tf, otel/otel-collector-config.yaml
This change does the following:
- Update the deployment document to 1) use TF_WORKSPACE to reduce the number of interactive prompts, 2) remove unneeded flags and commands
- Force all cloud run services to send traffic to the latest revision. If a developer manually touched a service, the next revision would deploy but no traffic would go to it. Leaving an older revision serving traffic (which could make debugging weird)
- Remove the BETA flags from the services in favor of the default GA value. Terraform kept trying to change it to BETA so something kept switching it. We don't need that field anymore
- Fix the health check for open telemetry. The latest version forces us to expose on 0.0.0.0. Otherwise, Cloud Run health check cannot access it. So it kept shutting down. Now it is fixed. …
=> Infrastructure fixups

.devcontainer/devcontainer.json
During a recent session, Dan and I used Live Share instead of sharing screens.
This allowed us to type directly into another's vs code and try things.
To learn more, check out the docs for Live Share: https://code.visualstudio.com/learn/collaboration/live-share
Marketplace link: https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare
This change allows it to be installed by default in the devcontainer.
=> Pre-install VS Code Live share

e2e/tests/overview-page.spec.ts, frontend/src/static/js/components/webstatus-overview-filters.ts, frontend/src/static/js/components/webstatus-overview-page.ts, frontend/src/static/js/index.ts, frontend/src/static/js/utils/csv.ts, frontend/src/static/js/utils/toast.ts
This PR provides feedback to the user while handling the export to CSV functionality, as requested by #511.
* When the "Export to CSV" button is clicked, it is disabled and changed to 'loading' state, and restored when done.
* If an error occurs during loading of the data or saving of the file, a toast alert will be displayed.
* Successful download results in the browser displaying the list of recent downloads, so no further confirmation is required.
This PR fixes #511
=> Provide UI feedback during export to CSV

.dev/auth/Dockerfile, .dev/auth/firebase.json, .dev/auth/manifests/pod.yaml, .dev/auth/manifests/service.yaml, .dev/auth/skaffold.yaml, DEVELOPMENT.md, Makefile
In preparation for supporting user accounts that
bacekd by Google Cloud Identity Platform, this
change adds the authentication emulator. This will allow developers to easily test out the
authentication and authorization flows via Github
locally.
Changes:
- Add Dockerfile that installs the emulator in the image.
- Add kubernetes manifests to deploy the image locally.
- Make the authentication emulator start up before the backend
- Expose the two ports for the emulator locally (9099, 9100)
- Update the development readme
You can see in the UI you can create a test user that signs in with github locally (the button will come in a future PR)
-  ![image](https://github.com/user-attachments/assets/37b2bdd5-94ea-46c6-8353-7c444c4095aa)
- …
=> Add Authentication Emulator

DEVELOPMENT.md, Makefile, util/cmd/load_test_users/main.go, util/go.mod, util/go.sum
This changes utilizes the API of the emulator to create users that will "Sign in With Github" locally.
In the future, we can associate these users in our database with certain roles.
The change makes sure it runs automatically when running playwright tests.
Depends on #534
=> Add util package to populate users automatically

frontend/src/static/index.html, frontend/src/static/js/components/test/webstatus-app.test.ts, frontend/src/static/js/components/test/webstatus-services-container.test.ts, frontend/src/static/js/components/webstatus-services-container.ts, frontend/src/static/js/contexts/firebase-app-context.ts, frontend/src/static/js/contexts/firebase-auth-context.ts, frontend/src/static/js/contexts/firebase-user-context.ts, frontend/src/static/js/services/test/webstatus-firebase-app-service.test.ts, frontend/src/static/js/services/test/webstatus-firebase-auth-service.test.ts, frontend/src/static/js/services/webstatus-firebase-app-service.ts, frontend/src/static/js/services/webstatus-firebase-auth-service.ts
This change adds two new services called `webstatus-firebase-app-service` and `webstatus-firebase-auth-service`.
These two services are responsible for handling the initialization of firebase app and firebase auth.
The settings for these two services are passed in as environment variables like other settings in index.html. The final index.html that is served by nginx fills it in one time before responding with index.html
webstatus-firebase-app-service:
- If the environment variables are not empty, it will create a firebase app and provide it via context.
webstatus-firebase-auth-service:
- Consumes the firebase app (if it was indeed created) and creates a firebase auth config.
- The firebase auth config is configured to do github authentication
- Also, sets up the user callback which will …
=> [1/3] Add services for firebase/app & firebase/auth

backend/pkg/httpserver/get_feature_test.go, backend/pkg/httpserver/get_features_test.go, lib/gcpspanner/feature_base_query.go, lib/gcpspanner/feature_search.go, lib/gcpspanner/feature_search_test.go, lib/gcpspanner/spanneradapters/backend.go, lib/gcpspanner/spanneradapters/backend_test.go, openapi/backend/openapi.yaml
This change adds a new optional string field to the BrowserImplementation component for the browser version that the feature became available.
The change also modifies the database query to return this data too
This completes the backend part of #306.
There still needs to be a frontend implementation to complete that issue.
---
<details>
<summary>Example payload that shows the browser version</summary>
<br>
```json
{
"data": [
{
"baseline": {
"low_date": "2024-07-09",
"status": "newly"
},
"browser_implementations": {
"chrome": {
"date": "2023-03-07",
"status": "available",
"version": "111"
},
"edge": {
"date": "2023-03-13",
"status": "available",
"version": "111"
},
"firefox": {
"date": "2024-07-09",
"status": "available",
"version": "128"
},
"safari": {
"date": "2023-03-27",
"status": …
```
=> Return browser version for feature implementation

DEVELOPMENT.md, frontend/manifests/pod.yaml, frontend/package.json, frontend/src/common/app-settings.ts, frontend/src/static/index.html, frontend/src/static/js/components/test/webstatus-app.test.ts, frontend/src/static/js/components/test/webstatus-services-container.test.ts, frontend/src/static/js/services/test/webstatus-app-settings-service.test.ts, infra/.envs/prod.tfvars, infra/.envs/staging.tfvars, infra/frontend/service.tf, infra/frontend/variables.tf, infra/main.tf, infra/variables.tf, package-lock.json
We are moving from Google Sign In to Google Cloud Identity Platform.
This change deletes all references to Google Sign In configuration.
=> [3/3] Clean up Google Sign In references

frontend/src/static/js/components/webstatus-overview-filters.ts
This should resolve #570.  It adds an `available_on` term to the autocomplete vocabulary.
This depends on #568.
=> Add available_on to autocomplete

antlr/FeatureSearch.g4, antlr/FeatureSearch.md, lib/gcpspanner/feature_base_query.go, lib/gcpspanner/feature_search_query.go, lib/gcpspanner/feature_search_test.go, lib/gcpspanner/searchtypes/features_search_parse_test.go, lib/gcpspanner/searchtypes/features_search_visitor.go, lib/gcpspanner/searchtypes/searchtypes.go
This PR introduces a new `available_date` query, enabling users to search for features that became available within a specified date range. This functionality is similar to the existing `baseline_date` query.
The antlr4 grammar has been expanded to accommodate this new term.
The generated Go code now uses a new custom method `VisitDateRangeQuery` that allows the generated `VisitBaseline_date_term` and `VisitAvailable_date_term` methods to pass in which identifier type to use while building the query's intermediate representation tree.
On the spanner side, a new JOIN has been added to base joins to create a browser_info alias that will allow us to do the filtering by available_date. An added benefit of this allowed us to replace existing column generation with data from browser_info. …
=> Add available_date query

images/nodejs_service.Dockerfile
Some workstations change the permission of the files. In docker, we can change that during image build time.
This change does that.
It adds +x to only the directories. And +r to everything.
=> Fix permissions for assets

antlr/FeatureSearch.g4, antlr/FeatureSearch.md, lib/gcpspanner/feature_search_query.go, lib/gcpspanner/feature_search_test.go, lib/gcpspanner/searchtypes/features_search_parse_test.go, lib/gcpspanner/searchtypes/features_search_visitor.go, lib/gcpspanner/searchtypes/searchtypes.go
This commit introduces a more precise way to filter features based on their availability date in a specific browser.  The existing `available_date` query is enhanced to optionally accept a browser prefix, enabling queries like `available_date:chrome:2023-01-01..2024-01-01` to find features that became available specifically in Chrome within the given date range.
This addresses a potential inaccuracy in the previous behavior where `available_date` combined with `available_on` could include features that were initially released in other browsers. The new syntax provides clarity and flexibility for users to express their search intent more accurately.
Additionally, the ANTLR grammar and visitor code have been updated to handle the new syntax, and the `availableDateFilter` function has been …
=> Fix available_date query to support browser-specific filtering

lib/gcpspanner/baseline_status.go, lib/gcpspanner/baseline_status_test.go, lib/gcpspanner/browser_availabilities.go, lib/gcpspanner/browser_availabilities_test.go, lib/gcpspanner/browser_releases.go, lib/gcpspanner/browser_releases_test.go, lib/gcpspanner/client.go, lib/gcpspanner/get_feature.go, lib/gcpspanner/web_features.go, lib/gcpspanner/wpt_run.go, lib/gcpspanner/wpt_run_test.go
In preparation for adding new tables to support feature groups and snapshots, I identified repetitive code patterns in our Spanner client logic. This was also flagged by the dupl linter.
This change introduces a more reusable and maintainable approach to handling upsert operations (insert or update) in our Spanner interactions.
Key changes
- entityMapper interface: Establishes the core mapping between external structs and their corresponding Spanner representations, along with methods for key retrieval, select queries, and table identification.
- writeableEntityMapper & writeableEntityMapperWithIDRetrieval interfaces: Extend entityMapper to handle merging data during updates and optionally retrieving entity IDs.
- entityWriter & entityWriterWithIDRetrieval structs: Implement the writeable …
=> Refactor: Centralize Upsert Logic into Reusable Generic

infra/storage/spanner/migrations/000006.sql, lib/gcpspanner/group_descendants.go, lib/gcpspanner/group_descendants_test.go, lib/gcpspanner/groups.go, lib/gcpspanner/groups_test.go, lib/gcpspanner/web_feature_groups.go, lib/gcpspanner/web_feature_groups_test.go
Depends on #593 
**Description:**
This PR introduces the foundational schema and data access layer for managing WebDX Groups and their associations with Web Features in Spanner. This is the beginning of #299 to support only the groups storage and filtering. (Snapshot schema will come separately)
**Key Changes**
* **Schema:**
* Created the `WebDXGroups` table to store group metadata.
* Created the `WebFeatureGroups` table to map web features to their associated groups.
* Created the `WebDXGroupDescendants` to include the descendant group IDs for efficient querying
* **Data Access Layer:**
* Implemented `UpsertGroup` and `GetGroupIDFromGroupKey` methods in the `Client` struct to interact with the `WebDXGroups` table.
* Implemented `UpsertWebFeatureGroup` to manage feature-group mappings in …
=> [1/4] Add support for WebDX Groups, Feature-Group Mappings &  Group Descendants

antlr/FeatureSearch.g4, antlr/FeatureSearch.md, lib/gcpspanner/feature_search_query.go, lib/gcpspanner/feature_search_test.go, lib/gcpspanner/searchtypes/features_search_parse_test.go, lib/gcpspanner/searchtypes/features_search_visitor.go, lib/gcpspanner/searchtypes/searchtypes.go
Depends on #595 
This PR enhances the feature search functionality by introducing a new `group` query term.  Users can now search for features belonging to a specific group and any of its descendant groups in the web-features repository hierarchy. 
**New Query Functionality**
* Query: `group:css`
* Interpretation: Retrieves features belonging to the "css" group *and* any of its child or descendant groups (e.g., "grid").
**Implementation Details**
* **Grammar Expansion:** The ANTLR4 grammar has been extended to include the `group` query term.
* **Visitor Method:** A new `VisitGroup_term` method has been implemented to handle the parsing and generation of the intermediate representation for group queries.
**Future Considerations**
* While the current implementation includes descendant …
=> [3/4] Add Support for Group-Based Feature Search

infra/storage/spanner/migrations/000007.sql, lib/gcpspanner/snapshots.go, lib/gcpspanner/snapshots_test.go, lib/gcpspanner/web_feature_groups_test.go, lib/gcpspanner/web_feature_snapshots.go, lib/gcpspanner/web_feature_snapshots_test.go
**Description:**
This PR introduces the foundational schema and data access layer for managing WebDX Snapshots and their associations with Web Features in Spanner. This is the second half of #299 to support only the snapshot storage and filtering.
**Note**: Unlike groups, snapshots do not have any hierarchy. So it is a little simpler.
**Key Changes**
* **Schema:**
* Created the `WebDXSnapshots` table to store snapshot metadata.
* Created the `WebFeatureSnapshots` table to map web features to their associated snapshots.
* **Data Access Layer:**
* Implemented `UpsertSnapshot` and `GetSnapshotIDFromSnapshotKey` methods in the `Client` struct to interact with the `WebDXSnapshots` table.
* Implemented `UpsertWebFeatureSnapshot` to manage feature-snapshot mappings in the `WebFeatureSnapshots` …
=> [1/5] Add support for WebDX Snapshot & Feature-Snapshot Mappings

lib/gcpspanner/spanneradapters/web_feature_groups_consumer.go, lib/gcpspanner/spanneradapters/web_feature_groups_consumer_test.go, lib/gcpspanner/spanneradapters/web_feature_snapshots_consumer.go, lib/gcpspanner/spanneradapters/web_feature_snapshots_consumer_test.go
Depends on #599 
Similar to `groups`, `snapshots` are a new top-level data container from the web features repository.
**Description:**
This PR introduces the `WebFeatureSnapshotConsumer` to process and store snapshot-related data from the WebDX web features repository. It builds upon the previously added `WebDXSnapshots` and `WebFeatureSnapshots` tables to establish relationships between web features and their associated snapshots.
**Key Functionality**
* **Feature-Snapshot Mapping:** It establishes the connections between web features and their corresponding snapshots, storing this information in the `WebFeatureSnapshots` table.
**Benefits**
* **Efficient Data Processing:** The consumer ensures correct insertion order for snapshots
* **Seamless Integration:** It integrates smoothly with …
=> [2/5] Implement Web Feature Snapshots Consumer

antlr/FeatureSearch.g4, antlr/FeatureSearch.md, lib/gcpspanner/feature_search_query.go, lib/gcpspanner/feature_search_test.go, lib/gcpspanner/searchtypes/features_search_parse_test.go, lib/gcpspanner/searchtypes/features_search_visitor.go, lib/gcpspanner/searchtypes/searchtypes.go
Depends on #600 
This PR enhances the feature search functionality by introducing a new `snapshot` query term.  Users can now search for features belonging to a specific snapshot in the web-features repository hierarchy.
**New Query Functionality**
* Query: `snapshot:ecmascript-5`
* Interpretation: Retrieves features belonging to the "ecmascript-5" snapshot.
**Implementation Details**
* **Grammar Expansion:** The ANTLR4 grammar has been extended to include the `snapshot` query term.
* **Visitor Method:** A new `VisitSnapshot_term` method has been implemented to handle the parsing and generation of the intermediate representation for snapshot queries.
=> [3/5] Add Support for Snapshot-Based Feature Search

workflows/steps/services/web_feature_consumer/cmd/server/main.go, workflows/steps/services/web_feature_consumer/pkg/httpserver/server.go, workflows/steps/services/web_feature_consumer/pkg/httpserver/server_test.go
Depends on #601 
This change makes the web features workflow make the call to insert the snapshots.
It leverages methods from previous PRs.
=> [4/5] Use new WebFeatureSnapshotConsumer in workflow

e2e/tests/overview-page.spec.ts, frontend/src/static/js/components/webstatus-overview-filters.ts, frontend/src/static/js/components/webstatus-typeahead.ts
This should resolve #261.  The webstatus-overview-filters element now adds a document keyup listener that looks for a `/` key pressed while the user is not in a dialog, menu, input, or textarea.
=> Typing slash focuses on searchbox.

.golangci.yaml, workflows/steps/services/common/repo_downloader/pkg/targz/archive.go
golangci-lint recently updated. It flags one error and one warning.
The error is an overflow error. You can see examples of how to fix it in the linter itself [1]. This change adds the bounds check which satisfies the linter.
The warning was to let us know that linter was deprecated and to switch to another. This change does that.
[1] https://github.com/securego/gosec/pull/1194/files#diff-f7279b9a692123f375cfadc43e1cd48a2b1679b908b90a84a9d6b151a854b745
=> Fix new lint error and warning

frontend/src/static/js/components/test/webstatus-overview-cells.test.ts, frontend/src/static/js/components/webstatus-overview-cells.ts
Currently the projected date string is appended with literal `30`.
This change converts the string from the date string to a Date object then adds 30 months to it.
Other changes:
- Add tests to assert render behavior for the combinations of column options for widely available, newly available and limited availability features.
- Add helpers formatDate and formatDateString to ensure consistent string formatting for the date.
=> Fix projected high date offset

infra/storage/spanner/migrations/000008.sql
This schema will enable efficient storage and querying of UMA telemetry data, specifically focusing on Chromium enums and their associated metrics.
Part of splitting up #616 
ChromiumHistogramEnums:
- Stores histogram names (e.g., `WebDXFeatureObserver`) with a generated UUID as the primary key.
- Designed to support multiple histogram types in the future.
- Adds a calculated lowercase column for case-insensitive searching.
ChromiumHistogramEnumValues:
- Stores the values within a given enum.
- Each entry includes a generated UUID, a foreign key referencing `ChromiumHistogramEnums`, the `BucketID`, and a human-readable `Label`.
WebFeatureChromiumHistogramEnumValues:
- Maps web features to `ChromiumHistogramEnumValues`.
- Specifically designed for the `WebDXFeatureObserver` enum. …
=> Add Spanner schema for UMA and Chromium Enums

lib/auth/gcp_token_generator.go, lib/auth/gcp_token_generator_test.go, lib/go.mod
This helper code is taken directly from
https://cloud.google.com/docs/authentication/get-id-token#metadata-server
It will be needed by the uma export service that will come in a future PR (you can see it in action in #616). This is similar to the fetch_id_token that happens on [ChromeStatus](https://github.com/GoogleChrome/chromium-dashboard/blob/8fd512af666290e13173176268b9a4e28bbc9c63/internals/fetchmetrics.py#L53)
FindCredentials is a method to get credentials from the metadata-server (found only when on GCP infra). As a result, there is a skipped test that will need to be run directly on GCP infra. (helpful if we move to GCP Cloud Build)
=> Helper to get credentials while on GCP infra

lib/gcpspanner/chromium_histogram_enum_values.go, lib/gcpspanner/chromium_histogram_enum_values_test.go, lib/gcpspanner/chromium_histogram_enums.go, lib/gcpspanner/chromium_histogram_enums_test.go
This change builds on the landed schema changes in #665.
Background:
- This change adds functionality to store and retrieve Chromium Histogram Enums and their values in Spanner. This data will be used in future changes to associate enum values with feature keys and store daily metrics.
This is the first part of the background where we are only storing the enum and enum values from the enums.xml file.
Table: ChromiumHistogramEnums
- It implements the writeableEntityMapperWithIDRetrieval [interface](https://github.com/GoogleChrome/webstatus.dev/blob/976ac09c7431204205970a566ef94db42b8e4456/lib/gcpspanner/client.go#L202-L205)
- Expose two methods:
- UpsertChromiumHistogramEnum - for upserting values
- GetIDFromChromiumHistogramKey - for getting the internal ID since we will be using the ID …
=> Add Spanner functionality to store and retrieve Chromium Histogram Enums and EnumValues

workflows/steps/services/chromium_histogram_enums/go.mod, workflows/steps/services/chromium_histogram_enums/workflow/chromium_codesearch_enum_fetcher.go, workflows/steps/services/chromium_histogram_enums/workflow/chromium_codesearch_enum_fetcher_test.go, workflows/steps/services/chromium_histogram_enums/workflow/chromium_codesearch_enum_parser.go, workflows/steps/services/chromium_histogram_enums/workflow/chromium_codesearch_enum_parser_test.go
Add logic to:
1. Fetch enums from the chromium codesearch
2. Parse the data into our metricdatatypes.HistogramMapping
This fetch and parse logic is inspired by
ChromeStatus's [logic](https://github.com/GoogleChrome/chromium-dashboard/blob/f367dd0690b857c85453c67f9d388f2b08797e6c/internals/fetchmetrics.py#L253-L282).
Part of split up of #616
Parent PR: #669
=> Fetch and parse histogram enum files

workflows/steps/services/uma_export/go.mod, workflows/steps/services/uma_export/workflow/http_metrics_fetcher.go, workflows/steps/services/uma_export/workflow/http_metrics_fetcher_test.go, workflows/steps/services/uma_export/workflow/xssi_metrics_parser.go, workflows/steps/services/uma_export/workflow/xssi_metrics_parser_test.go
Add logic to:
1. Make a request to the UMA Export server
2. Remove the XSSI prefix
3. Parse the JSON response into our metricdatatypes.BucketDataMetrics
This fetch and parse logic is inspired by
ChromeStatus's [uma export logic](https://github.com/GoogleChrome/chromium-dashboard/blob/f367dd0690b857c85453c67f9d388f2b08797e6c/internals/fetchmetrics.py#L104-L116).
Part of split up of #616
Parent PR: #669
=> Fetch and parse UMA export server responses

lib/gcpspanner/daily_chromium_histogram_metric_capstones.go, lib/gcpspanner/daily_chromium_histogram_metric_capstones_test.go, lib/gcpspanner/daily_chromium_histogram_metrics.go, lib/gcpspanner/daily_chromium_histogram_metrics_test.go
This change builds on the landed schema changes in #665.
Background:
This change adds functionality store daily metrics from UMA export server. To prevent redundant requests, we also store a capstone (similar to ChromeStatus). The capstone lets us know if we already processed data from the UMA server for a given day.
Table: DailyChromiumHistogramMetrics
- Implements the writeableEntityMapper interface
- Exposes one method:
- UpsertDailyChromiumHistogramMetric - to upsert the metric for a given histogram enum value
Table: DailyChromiumHistogramEnumCapstones
- Implements the writeableEntityMapper interface
- Exposes two methods:
- HasDailyChromiumHistogramCapstone - to check if the metrics for a given day have already been processed.
- UpsertDailyChromiumHistogramCapstone - for inserting …
=> Add Spanner functionality to store and retrieve daily UMA metrics

lib/gcpspanner/web_feature_chromium_histograms.go, lib/gcpspanner/web_feature_chromium_histograms_test.go
This change builds on the landed schema changes in #665.
This change adds functionality to store mappings between web features (Table: WebFeatures) and Enum Values (Table: ChromiumHistogramEnumValues)
Since the metrics are given by enum value ID, this mapping will be useful for looking up the metrics for a given features
Table: WebFeatureChromiumHistogramEnumValues
- Implements the writeableEntityMapper interface
- Exposes one method:
- UpsertWebFeatureChromiumHistogramEnumValue - used to insert the mappings
Part of splitting up #616
=> Add Spanner functionality to store mappings between Enums & Features

workflows/steps/services/chromium_histogram_enums/workflow/job_processor.go, workflows/steps/services/chromium_histogram_enums/workflow/job_processor_test.go
Building on the refactoring done in #673, this adds the generic implementation for how the Chromium Histogram workflow should run.
1. Fetch the enums.
2. Parse the enums.
3. Save the enums.
Other structs actually implement the EnumsFetecher, EnumsParser and HistogramStorer interfaces.
Part of splitting up #616
=> Add JobProcessor interface for Chromium Enum workflow

workflows/steps/services/uma_export/go.mod, workflows/steps/services/uma_export/go.sum, workflows/steps/services/uma_export/workflow/job_processor.go, workflows/steps/services/uma_export/workflow/job_processor_test.go
Building on the refactoring done in #673, this adds the generic implementation for how the UMA workflow should run.
1. Check capstone.
2. Fetch data.
3. Parse the data.
4. Save the metrics.
5. Save the capstone.
Other structs actually implement the metricStorer and metricFetcher interfaces.
Part of splitting up #616
=> Add JobProcessor interface for UMA workflow.

infra/modules/go_image/main.tf, infra/modules/go_image/outputs.tf, infra/modules/go_image/providers.tf, infra/modules/go_image/variables.tf, infra/modules/job/main.tf, infra/modules/job/outputs.tf, infra/modules/job/providers.tf, infra/modules/job/variables.tf, infra/modules/single_stage_go_workflow/main.tf, infra/modules/single_stage_go_workflow/providers.tf, infra/modules/single_stage_go_workflow/variables.tf, infra/modules/single_stage_go_workflow/workflows.yaml.tftpl
Upon doing #616, I saw I was once again creating a lot of terraform files to deploy the jobs. And a lot of the terraform was a repeat of previous jobs with slight name tweaks.
This change introduces three new reusable modules:
- go_image - useful for any of the Go images built for the project
- job - useful for deploying an image to a cloud run job. creates the service account and adds permissions as needed
- single_stage_go_workflow - all of the workflows are single jobs (not a chain of multiple jobs.). This adds a common workflow template for one job, creates a schedule and gives it the permission to invoke the job.
After this change has landed, developers can simply make a change like the following to deploy a job (instead of creating multiple files):
```
module "bcd_workflow" {
source …
```
=> Refactor: Make reusable modules for creating jobs in terraform

lib/gcpspanner/spanneradapters/chromium_historgram_enum_consumer.go, lib/gcpspanner/spanneradapters/chromium_historgram_enum_consumer_test.go, lib/gcpspanner/spanneradapters/uma_metric_consumer.go, lib/gcpspanner/spanneradapters/uma_metric_consumer_test.go, lib/go.mod
Add two new spanner adapters. One for the uma export job and one for the chromium enum job.
Reminder: These adapters translate commands from the services/jobs to the storage layer. If there is any necessary conversion, it would happen here.
This part of the split up of #616
=> Add spanner adapters for uma and chromium enums

infra/.envs/prod.tfvars, infra/.envs/staging.tfvars, infra/ingestion/variables.tf, infra/ingestion/workflows.tf, infra/main.tf, infra/variables.tf
This change adds the terraform to deploy the new jobs from the #616 split up.
Times are random but UMA should happen after the chromium job.
=> Add terraform for uma and chromium jobs

lib/gcpspanner/daily_chromium_histogram_metrics.go, lib/gcpspanner/spanneradapters/uma_metric_consumer.go, workflows/steps/services/uma_export/workflow/job_processor.go, workflows/steps/services/uma_export/workflow/job_processor_test.go
1. Check if the data from UMA export has actual data in 200 response.
- Over the weekend, the process received a 200 response but no data. Then we marked the capstone even though there was no data. This makes sure there's data first. If no data, return early for that day.
2. Handle missing draft histograms. Currently, we don't store draft enums. So when we get data from uma export server for that enum bucket id, we won't find it. This skips those.
3. Fix wrapping an error SaveMetrics. Previously, we stopped returning the internal error. But this fixes the error wrap in errors.Join.
=> Bug fixes for UMA job_process

lib/gcpspanner/baseline_status.go, lib/gcpspanner/baseline_status_test.go
The initial implementation cautiously override each field of the row. While that is good for other tables, we can trust that the incoming data won't be incomplete/partial.
We need this because sometimes a feature that was previously thought to be baseline can actually not be baseline. And we need to revert that.
Addresses part of #515
=> Allow resetting of baseline status

DEPLOYMENT.md, frontend/src/common/app-settings.ts, frontend/src/static/index.html, frontend/src/static/js/components/test/webstatus-app.test.ts, frontend/src/static/js/components/test/webstatus-services-container.test.ts, frontend/src/static/js/services/test/webstatus-app-settings-service.test.ts, frontend/src/static/js/services/test/webstatus-firebase-auth-service.test.ts, frontend/src/static/js/services/webstatus-firebase-auth-service.ts, infra/.envs/prod.tfvars, infra/.envs/staging.tfvars, infra/auth/main.tf, infra/auth/outputs.tf, infra/auth/providers.tf, infra/auth/variables.tf, infra/frontend/service.tf, infra/frontend/variables.tf, infra/main.tf, infra/providers.tf, infra/variables.tf
This change configures Google Cloud Identity Platform (GCIP) for staging and production environments, enabling developers to deploy full-stack applications with GCIP to GCP.
Key changes include:
- Setting up a new GCIP tenant with a GitHub Provider for authentication.
- Modifying the frontend infrastructure module to utilize the new tenant and enable GitHub login.
- Updating frontend code to handle optional tenant IDs, allowing seamless transition between local and cloud environments.
This addresses the previous limitation of having GCIP configured only locally with the emulator.
=> Enable Google Cloud Identity Platform for staging and production

.dev/spanner/Dockerfile, lib/gcpspanner/client_test.go
In the spanner emulator, a version of wrench is downloaded. But it is hardcoded to amd64.
This change uses the auto populated TARGETARCH argument.
Now, we know which architecture to use when downloading the wrench CLI. Should fix the problem for those running the repo on a Macbook.
See: https://github.com/GoogleChrome/webstatus.dev/issues/720#issuecomment-2394365939
=> Use Target Architecture Argument for docker build

infra/.envs/prod.tfvars, infra/.envs/staging.tfvars, infra/backend/service.tf, infra/backend/variables.tf, infra/frontend/service.tf, infra/frontend/variables.tf, infra/main.tf, infra/variables.tf
This PR updates the Terraform configuration for our Cloud Run deployment to enforce hostname-based routing using host_rule within the google_compute_url_map resource.
We observed in the logs that our website was being served on unintended hostnames. This could potentially be due to:
- Misconfigured DNS: Incorrect DNS records could be directing traffic to our load balancer from unintended domains.
- Unintentional Traffic: Other services or users might be inadvertently sending traffic to our load balancer.
To mitigate this, we're implementing the following changes:
- host_rule: We're adding host_rule to the google_compute_url_map to explicitly define the allowed hostnames for our staging environment (website-webstatus-dev.corp.goog) and production environment (webstatus.dev). Same thing for …
=> Restrict Traffic to Allowed Hostnames for Cloud Run w/ Load Balancer

.dev/datastore/Dockerfile, .dev/datastore/manifests/pod.yaml, .dev/datastore/manifests/service.yaml, .devcontainer/devcontainer.json, DEVELOPMENT.md, Makefile, backend/manifests/pod.yaml, lib/gds/client_test.go, workflows/steps/services/common/repo_downloader/manifests/pod.yaml, workflows/steps/services/web_feature_consumer/manifests/pod.yaml, workflows/steps/services/wpt_consumer/manifests/job.yaml
Before this change:
Datastore and the redirect from `gcloud auth login` both use port 8085. Sometimes, a developer who is actively deploying and developing can get into a situation where port 8085 no longer works for one of the other. Meaning, either they cannot run `make dev_fake_data` or deploy anymore until they restart their devcontainer. This should help with that.
This change:
Changes datastore to use port 8086 instead everywhere.
- Why not change the port for gcloud auth login? I could not find instructions on the docs: https://cloud.google.com/sdk/gcloud/reference/auth/login
Other changes:
- Use calico for better networking.
- Why: My environment actually stopped working. When debugging, it was because the pods could not talk internally to each other. Calico is a popular container …
=> Use different port for datastore than gcloud auth

infra/.envs/prod.tfvars, infra/.envs/staging.tfvars, infra/backend/service.tf, infra/backend/variables.tf, infra/frontend/service.tf, infra/frontend/variables.tf, infra/main.tf, infra/variables.tf
By default cloud run will scale down to zero. Spin ups can hurt the SLO.
This change exposes variables for the minimum and maximum number of instances.
For prod, we set the min to 1. For staging, we set the min to 0 (for now)
For prod and staging, we set the max to 100. This is the default anyhow.
Depends on: #745
=> Add variables to tune scaling for backend & frontend

frontend/package.json, frontend/src/static/js/contexts/router-context.ts, package-lock.json
There's a dependabot alert on path-to-regexp which vaadin/router depends on.
https://github.com/GoogleChrome/webstatus.dev/security/dependabot/46
This change bumps the version of vaadin/router so that it uses the fixed version.
The new version of vaadin/router slightly changed due to the library using typescript (also going from v1.x.x to v2.x.x). As a result, there were small changes to fix that.
=> Upgrade @vaadin/router to resolve dependabot issue.

infra/storage/spanner/migrations/000009.sql, lib/gcpspanner/saved_search_user_roles.go, lib/gcpspanner/saved_searches.go, lib/gcpspanner/user_search_bookmarks.go
This commit introduces the following three new tables to the database schema:
- SavedSearches: Stores the saved searches, including their name, query, scope (user-specific or global), author, and timestamps.
- SavedSearchUserRoles: Manages the roles of users in relation to saved searches (e.g., owner, editor).
- UserSavedSearchBookmarks: Tracks which user-specific saved searches are bookmarked by which users.
These tables provide the foundation for managing saved searches, user roles, and bookmarks, enabling features like creating, retrieving, updating, and deleting saved searches, assigning roles, and bookmarking searches for easy access.
Fixes #765 
Split up of #766
=> feat: introduce SavedSearches, SavedSearchUserRoles, & UserSavedSearchBookmarks tables

.devcontainer/post_create.sh
Set the default umask to 022 within the devcontainer to ensure new files are created with read permissions for all users.
Additionally, recursively add read permission to all existing files in the devcontainer to ensure consistent access.
This prevents permission issues when working within the development container that otherwise would be set by a different umask on the host.
=> feat(devcontainer): adjust file permissions

lib/gcpspanner/client.go, lib/gcpspanner/daily_chromium_histogram_metric_capstones.go, lib/gcpspanner/wpt_run.go
This commit introduces several improvements to the Spanner client and adds support for removing entities:
- **Moved `GetKey` and `Table` methods:**  These methods are now part of the `writeableEntityMapper` interface, as they are only used for write operations. This clarifies the responsibility of each mapper type.
- **Simplified `createInsertMutation`:** Removed unnecessary error checking from the former `readRowErrorAndAttemptInsert` function, making it more versatile and reusable.
- **Added `createUpdateMutation`:**  This new function streamlines update operations.
- **Introduced `xxxWithTransaction` methods:** These methods enable chaining multiple actions within a single transaction for improved efficiency and consistency.
- **Added update row action:** This prepares the client for …
=> Refactor: Spanner client enhancements and new entityRemover

lib/gcpspanner/client.go, lib/gcpspanner/create_user_saved_search.go, lib/gcpspanner/create_user_saved_search_test.go, lib/gcpspanner/saved_search_user_roles.go, lib/gcpspanner/saved_searches.go, lib/gcpspanner/user_search_bookmarks.go
For creating:
- In the same transaction it will check:
- If the user does not owned too many saved searches.
- Add the user as an admin
- Add the new saved search as a bookmark
We also introduce the search config struct which holds an app wide configuration for the max number of saved searches a user can have.
Fixes: #804
=> Add database method to create user saved search

lib/gcpspanner/saved_search_user_roles.go, lib/gcpspanner/update_user_saved_search.go, lib/gcpspanner/update_user_saved_search_test.go
It checks whether or not a user is an owner of the saved search through a reusable permissions checker.
If it passes, it will allow the update to go through.
=> Add database method for updating user saved search

lib/gcpspanner/feature_base_query.go, lib/gcpspanner/feature_search.go, lib/gcpspanner/feature_search_test.go, lib/gcpspanner/get_feature.go, lib/gcpspanner/spanneradapters/backend_test.go
Addresses #844 
This is a small change to update the features search spanner logic to query for a new `ChromiumUsage` field.
=> Add new ChromiumUsage field to features search spanner logic

infra/storage/spanner/migrations/000010.sql
This table logs when any browser is released. Then it records whether or not that the feature is supported. This is useful because the missing one implementation calculation occurs when another browser is released and not the target browser itself.
Fixes: #833
Is a split up of https://github.com/GoogleChrome/webstatus.dev/compare/missing-one-impl-count-db?expand=1
=> Add BrowserFeatureSupportEvents table

lib/gcpspanner/browser_availabilities.go, lib/gcpspanner/browser_feature_support_event.go, lib/gcpspanner/browser_feature_support_event_test.go, lib/gcpspanner/browser_releases.go, lib/gcpspanner/web_features.go
Depends on: #865
This method is the entrypoint to calculate the events stored in the BrowserFeatureSupportEvents table introduced in #865.
It reads all of the web features, browser releases and feature availabilities. With that, it builds the event log.
In order to read all that data, small helper methods were created to assist.
This PrecalculateBrowserFeatureSupportEvents method does not take in any input and just uses existing table data. Since this is the entrypoint method that will be called from the workflow package, it is a public method.
This PR is a split up of https://github.com/GoogleChrome/webstatus.dev/compare/missing-one-impl-count-db?expand=1
Fixes #834
=> Add PrecalculateBrowserFeatureSupportEvents method

lib/gcpspanner/spanneradapters/backend.go, lib/gcpspanner/spanneradapters/backend_test.go, openapi/backend/openapi.yaml
Fixes #845 
Additionally, a small fix in `lib/gcpspanner/spanneradapters/backend.go` is present.
=> Convert ChromiumUsage field to backend struct

lib/gcpspanner/spanneradapters/web_features_consumer.go, lib/gcpspanner/spanneradapters/web_features_consumer_test.go
This now mandates that the WebFeatureSpannerClient implements PrecalculateBrowserFeatureSupportEvents (which already happened in #872). Since the spanner client already implements this in that mentioned PR, we don't have to do anything else besides modify the expected interface.
Also, modified the tests to accomodate for the fact that we are calling that now.
Addresses: #836
=> Web Features workflow now calls Precalculate method for feature support events

Makefile
Right now, the Makefile target for the go openapi code only re-generates if the [openapi.yaml](https://github.com/GoogleChrome/webstatus.dev/blob/ddf30251ca40fc008f338d33c0fe31bdd0b61984/Makefile#L108-L119) itself has changed.
But if the underlying libraries changed, a developer's environment will fail to re-generate.
This change:
- Now, we just wipe out all the generated openapi Go code which guarantees re-generation during `make build` (which happens before `make start-local`)
The typescript openapi code doesn't have the same problem because the rule for it is a little different.
=> Call clean-openapi before generating new opeanpi Go code.

lib/gcpspanner/missing_one_implementation.go, lib/gcpspanner/missing_one_implementation_test.go
This is the spanner method that will power the missing one implementation graph.
It uses the pre calculated results from the BrowserFeatureSupportEvents table.
Features:
- It allows the caller to pass in arbitrary set of browsers to compare against.
- It has a string pagination token that is decoded and used to continue paging for results
- It returns the results in DESC order of the Release Date
This method is similar to:
1. the [ListMetricsForFeatureIDBrowserAndChannel](https://github.com/GoogleChrome/webstatus.dev/blob/dd754efe5e2fa27cc80542fbacd41886e765b7ba/lib/gcpspanner/wpt_run_feature_metric.go#L418-L494) method used to get the results for the WPT metrics that power the chart on the feature detail, and
2. the [ListBrowserFeatureCountMetric](https://github.com/GoogleChrome/webstatus …
=> Add ListMissingOneImplCounts spanner method

infra/modules/single_stage_go_workflow/main.tf, infra/modules/single_stage_go_workflow/workflows.yaml.tftpl
Currently: When the GCP workflow calls the cloud run job, the cloud run job runs with a certain timeout configured. But the workflow uses the default timeout.
This leads to the workflow being marked as failed within the default time. But the job actually is still running.
This change makes it so the workflow uses the same timeout as the job.
=> Pass timeout config to GCP workflow

lib/gcpspanner/client.go, util/cmd/load_fake_data/main.go
The spanner emulator does not currently support the batch write API. Probably because it is in Preview on GCP. But we should leverage this here for our workflows when possible.
This new interface is used by the Client. Upon construction, it determines which batch writer to use.
=> Add batchWriter interface for spanner

lib/gcpspanner/browser_availabilities.go, lib/gcpspanner/browser_feature_support_event.go, lib/gcpspanner/browser_releases.go, lib/gcpspanner/client.go, lib/gcpspanner/web_features.go
This change adds a generic concurrent batch writer. This calls the BatchWriteMutations method from #889 
Background: During testing in GCP, I saw that each batch write call has a limit but we can increase throughput by running concurrent batch writes.
By default, we set the batch size to 10000 entities and 8 concurrent batch writers. In the future, we can allow spanner clients to configure these based on system settings.
=> Add concurrent batch writer + have browser feature support event use it

infra/ingestion/workflows.tf, lib/gcpspanner/browser_feature_support_event.go, lib/gcpspanner/browser_feature_support_event_test.go, lib/gcpspanner/missing_one_implementation_test.go, lib/gcpspanner/spanneradapters/web_features_consumer.go, lib/gcpspanner/spanneradapters/web_features_consumer_test.go, util/run_job.sh, workflows/steps/services/web_feature_consumer/cmd/job/main.go, workflows/steps/services/web_feature_consumer/manifests/job.yaml, workflows/steps/services/web_feature_consumer/pkg/workflow/web_features_worker.go, workflows/steps/services/web_feature_consumer/pkg/workflow/web_features_worker_test.go
This is similar to the DATA_WINDOW_DURATION environment variable used in the WPT workflow. [source](https://github.com/search?q=repo%3AGoogleChrome%2Fwebstatus.dev%20DATA_WINDOW_DURATION&type=code)
We do this so that between local and gcp environments, we can control how much data is loaded automatically. Otherwise, the local environment could be overwhelmed by trying to consume all the data.
In GCP environments, we look back 30 years (more than enough time)
In local environments, we look back only half a year.
=> Add DATA_WINDOW_DURATION for web features workflow

backend/pkg/httpserver/list_aggregated_feature_support.go, backend/pkg/httpserver/list_missing_one_implementation_counts.go, backend/pkg/httpserver/list_missing_one_implementation_counts_test.go, backend/pkg/httpserver/server.go, backend/pkg/httpserver/server_test.go, lib/gcpspanner/spanneradapters/backend.go, lib/gcpspanner/spanneradapters/backend_test.go
Fixes #880
This change adds the spanner adapter conversion layer for the missing one implementation endpoint. This converts the data from spanner to the expected missing one implementation page that is documented in the openapi yaml for the endpoint.
This change has the http layer call this layer for the endpoint.
Heavily inspired by:
- [backend/pkg/httpserver/list_aggregated_feature_support.go](https://github.com/GoogleChrome/webstatus.dev/blob/main/backend/pkg/httpserver/list_aggregated_feature_support.go)
- The [ListBrowserFeatureCountMetric method in lib/gcpspanner/spanneradapters/backend.go](https://github.com/GoogleChrome/webstatus.dev/blob/40b461b550bbb32b432a6dd219e9ccf94b249d23/lib/gcpspanner/spanneradapters/backend.go#L99-L133)
Other changes:
- Fix log statement in …
=> Add plumbing between spanner & http for missing one implementation

antlr/FeatureSearch.g4, antlr/FeatureSearch.md, lib/gcpspanner/feature_search_query.go, lib/gcpspanner/searchtypes/features_search_parse_test.go, lib/gcpspanner/searchtypes/features_search_visitor.go, lib/gcpspanner/searchtypes/searchtypes.go
Fix [#786](https://github.com/GoogleChrome/webstatus.dev/issues/786). Add a search atom `id` to the parser. `id` searches for features whose feature identifier matches the search value exactly.
Also a drive-by change for the `Snapshot_termContext` switch case in `visit()`.
=> Add id term to featuresearch.g4

frontend/src/static/js/components/webstatus-overview-filters.ts
A follow-up for 917. A part of https://github.com/GoogleChrome/webstatus.dev/issues/297
=> Add id term to the frontend vocabulary

util/go.mod, workflows/steps/services/uma_export/workflow/http_metrics_fetcher.go, workflows/steps/services/uma_export/workflow/http_metrics_fetcher_test.go, workflows/steps/services/uma_export/workflow/job_processor.go, workflows/steps/services/uma_export/workflow/job_processor_test.go
Currently, it only gets the latest metrics. However, we should be sending the date
[Example](https://github.com/GoogleChrome/chromium-dashboard/blob/19f27ae20f81eaa2106360dd8e2e66ee82547b60/internals/fetchmetrics.py#L92) of doing it in ChromeStatus.
The date provided to the uma export server needs to be in the following format YYYYMMDD. To accomplish that in [Go](https://go.dev/src/time/format.go), we have to specify the format as `20060102`
=> Fix the UMA metrics fetcher

frontend/src/static/js/components/test/webstatus-overview-content.test.ts, frontend/src/static/js/components/test/webstatus-sidebar-menu.test.ts, frontend/src/static/js/components/webstatus-overview-content.ts, frontend/src/static/js/components/webstatus-sidebar-menu.ts, frontend/src/static/js/utils/constants.ts
#764 and a follow-up for https://github.com/GoogleChrome/webstatus.dev/pull/931. Add a custom overview page title and description when it shows a bookmark query.
Mock UI:
It is a similar placement between title and description to feature page:
=> Overview page UI for bookmarks

frontend/src/static/js/components/test/webstatus-overview-table.test.ts, frontend/src/static/js/components/webstatus-overview-content.ts, frontend/src/static/js/components/webstatus-overview-table.ts, frontend/src/static/js/utils/constants.ts
A follow-up for #764, sort the features in the overview page based on the bookmark query order.
- Given that the number of features should be < 20, the sorting is implemented on the frontend
- Again given the number, the algorithm for finding a feature is brute force
- Only support `id` and `name` at the moment
- If there are features missing after sorting, revert to the default order
=>  Sort displayed features based on bookmark query

infra/storage/spanner/migrations/000013.sql, lib/gcpspanner/client.go, lib/gcpspanner/create_user_saved_search.go, lib/gcpspanner/create_user_saved_search_test.go, lib/gcpspanner/get_user_saved_search.go, lib/gcpspanner/get_user_saved_search_test.go, lib/gcpspanner/saved_searches.go, lib/gcpspanner/update_user_saved_search.go, lib/gcpspanner/update_user_saved_search_test.go, lib/gcpspanner/user_search_bookmarks_test.go
Fixes #951
This change modifies the database schema to add an optional description column to the existing saved searches table. This new column will allow users to store a brief description of their saved search, making it easier to understand its purpose later.
Other changes:
- Add new type: OptionallySet. Previously we allowed callers to let the spanner layer know that we want to update one field by setting a pointer. That worked on fields that were not optional. But since the description can be null, I added this new type to capture that.
- Modified tests to use the new description field and ensure that saving and retrieving descriptions works as expected.
=> Add description column to saved searches table

lib/gcpspanner/chromium_histogram_enum_values_test.go, lib/gcpspanner/client.go, lib/gcpspanner/daily_chromium_histogram_metrics.go, lib/gcpspanner/daily_chromium_histogram_metrics_test.go, lib/gcpspanner/spanneradapters/uma_metric_consumer.go, lib/gcpspanner/spanneradapters/uma_metric_consumer_test.go, lib/gcpspanner/wpt_run_feature_metric.go
Previously, we returned an error for any error when ingesting the metrics.
There are certain errors we should warn instead of stopping execution.
Added DailyChromiumHistogramMetrics specific errors and modified the logic to check for errors. A subset of 2 errors will warn instead of returning the error back up the stack. This resolves an existing TODO comment.
Other changes:
- Use ErrQueryReturnedNoResults in places it should be to be consistent with other places. ([example](https://github.com/GoogleChrome/webstatus.dev/blob/2901887e4c0201aa40c0a2304c24669c590f026a/lib/gcpspanner/client.go#L378-L380))
=> Warn for certain DailyChromiumHistogramMetrics errors

frontend/src/static/js/components/webstatus-overview-content.ts, frontend/src/static/js/components/webstatus-overview-pagination.ts, frontend/src/static/js/components/webstatus-overview-table.ts
Use `@property` for public reactive properties. A drive-by fix when I was investigating the timing issue at https://github.com/GoogleChrome/webstatus.dev/pull/992#pullrequestreview-2509041075.
These properties are meant to be public and modified from outside of the component through HTML attributes. While both trigger re-renders, `state` should be used for internal component state, such as https://github.com/GoogleChrome/webstatus.dev/blob/dd102175d49b248521e4ee26e73490abf41dcefd/frontend/src/static/js/components/webstatus-overview-page.ts#L52
=> Use property for public reactive properties

frontend/src/static/js/components/webstatus-overview-page.ts
Fix the timing bug mentioned in https://github.com/GoogleChrome/webstatus.dev/pull/992#pullrequestreview-2509041075. There is a weird Async Tasks cache issue, possibly due to [Saves the last completion value or error of the task function](https://lit.dev/docs/data/task/#features). It reassigns an old value of `this.TasktaskTracker` after `New Task` is defined but before the callback executes.
As a result, the pending UI on the overview page loads correctly when users navigate.
=> Fix Async Tasks data cache issue

.devcontainer/Dockerfile, Makefile, images/go_service.Dockerfile, images/nodejs_service.Dockerfile
There are some existing dockerfile lint warnings. This commit fixes them.
Example: https://github.com/GoogleChrome/webstatus.dev/actions/runs/12552250381/job/34997931125?pr=1022#step:9:10621
To future proof it, it also adds a makefile target that does the same check.
Notable things fixed:
- https://docs.docker.com/reference/build-checks/undefined-var/
- https://docs.docker.com/reference/build-checks/legacy-key-value-format/
- https://docs.docker.com/reference/build-checks/json-args-recommended/
- https://docs.docker.com/reference/build-checks/from-as-casing/
All the checks can be found on this page: https://docs.docker.com/reference/build-checks/
=> Fix dockerfile warnings and add lint command

frontend/package.json, frontend/rollup.config.mjs, frontend/src/static/js/components/test/webstatus-feature-page.test.ts, frontend/src/static/js/components/test/webstatus-gchart.test.ts, frontend/src/static/js/components/webstatus-feature-page.ts, frontend/src/static/js/components/webstatus-overview-filters.ts, frontend/src/static/js/components/webstatus-sidebar-menu.ts, frontend/src/static/js/services/webstatus-firebase-app-service.ts, frontend/web-test-runner.config.mjs
Background:
Upon running the frontend tests, you can see there are many unexpected logs being printed out. This ranges from:
1. 404 Network Requests ([Example](https://github.com/GoogleChrome/webstatus.dev/actions/runs/12553689104/job/35001422582#step:6:10143))
2. Uncaught exceptions ([Example](https://github.com/GoogleChrome/webstatus.dev/actions/runs/12553689104/job/35001422582#step:6:10178))
3. Inefficient re-rendering ([Example](https://github.com/GoogleChrome/webstatus.dev/actions/runs/12553689104/job/35001422582#step:6:10338))
Check the full log for all the errors.
**Case 1**
Problem:
- Tests are missing static resources
Remedy:
- Copy the static resources to same folder as the compiled tests with new `cp-imgs` npm target.
- Simplified rollup config by now only needing one copy …
=> Fix frontend test errors

antlr/FeatureSearch.g4, lib/gcpspanner/searchtypes/features_search_parse_test.go, lib/gcpspanner/searchtypes/features_search_visitor.go
When a string is missing the colon or value for a term, the parser still reaches the visitor method with a nil value node. This adds nil checks to handle these cases and returns an error.  This should cause the backend to return 4xx errors instead of 5xx errors.
Test cases have been added to address the reported issues in #286.
Possible future improvement: Explore grammar modifications to prevent these invalid inputs at the parser level.
Other changes:
- Adjust grammar to allow `(` or `)` only in the quoted words to support queries like this: `name:"has()" OR name:light-dark` (also reported in #286)
=> Handle missing values in grammar terms with nil checks in visitor

frontend/src/static/js/utils/constants.ts
Closes #806
This will lead users to the different templates instead of the empty one.
=> Change issue link from /new to /new/choose

lib/gcpspanner/feature_base_query.go, lib/gcpspanner/feature_search_query.go, lib/gcpspanner/feature_search_test.go, lib/gcpspanner/get_feature_query.go
Closes #791 
This adds a new filter to sort specifically by a browser's feature availability date.
It is a special sort like the existing one where we sort by WPT score for a given browser. That one requires an optional join just like that.
=> Add spanner logic to sort by browser feature availability

frontend/src/static/js/components/test/webstatus-form-date-range-picker.test.ts, frontend/src/static/js/components/webstatus-form-date-range-picker.ts, frontend/web-test-runner.config.mjs
This component will be a reusable component for date range picking.
This takes mostly the implementation used on the feature detail page and puts it into this component.
Notable differences:
- Add max and min constraints for native <input> tag. This will help the user pick sensible dates by limiting the calendar dates.
- Displaying messages for invalid input.
- Reset invalid input back to a sane default.
- Emit events on successful date changes for start and end dates ([link](https://lit.dev/docs/composition/component-composition/#:~:text=When%20exchanging%20data%20with%20subcomponents%2C%20the%20general%20rule%20is%20to%20follow%20the%20model%20of%20the%20DOM%3A%20properties%20down%2C%20events%20up)).
- Adds a search button to apply the new dates. I was inspired by GCP metrics dashboard …
=> Add webstatus-form-date-range-picker component

frontend/src/static/js/components/test/webstatus-base-charts-page.test.ts, frontend/src/static/js/components/webstatus-base-charts-page.ts, frontend/src/static/js/components/webstatus-feature-page.ts, frontend/src/static/js/utils/urls.ts
BaseChartsPage is a component that all pages with charts can use. It provides a renderDateRangePicker() method that any child class can use in its main render method. It also centralizes the event handling for the start and end date changes.
We also rename the existing updateFeaturePageUrl util method to updatePageUrl. The BaseChartsPage component uses it to update the page's url appropriately when the date range changes.
Each child class can override things like the default dates if needed.
Split up of #1055
=> Add BaseChartsPage common component

.dev/auth/Dockerfile, .devcontainer/Dockerfile, .devcontainer/devcontainer.json, images/go_service.Dockerfile, images/nodejs_service.Dockerfile
Moves the devcontainer from bullseye to bookworm
Upgrade versions for various tools.
Update docker images. (Did not change the distribution for each one. Only updated to the latest). Also started to pin Nginx to its exact version.
=> Update components in devcontainer

backend/pkg/httpserver/get_features.go, backend/pkg/httpserver/get_features_test.go, backend/pkg/httpserver/list_aggregated_feature_support.go, backend/pkg/httpserver/list_aggregated_feature_support_test.go, backend/pkg/httpserver/list_aggregated_wpt_metrics.go, backend/pkg/httpserver/list_aggregated_wpt_metrics_test.go, backend/pkg/httpserver/list_chromium_usage.go, backend/pkg/httpserver/list_chromium_usage_test.go, backend/pkg/httpserver/list_feature_wpt_metrics.go, backend/pkg/httpserver/list_feature_wpt_metrics_test.go, backend/pkg/httpserver/list_missing_one_implementation_counts.go, backend/pkg/httpserver/list_missing_one_implementation_counts_test.go, backend/pkg/httpserver/server_test.go, lib/gcpspanner/spanneradapters/backend.go, lib/gcpspanner/spanneradapters/backend_test.go, lib/gcpspanner/spanneradapters/backendtypes/types.go
Background: This change is in response to some 500 errors I saw this week.
Currently, if a user passes an invalid page token, they will receive a 500 error. This is because the page token format is a Base64 encoded string that contains a format potentially unique to each endpoint, and its validity cannot be determined until the database tries to parse it.
This change improves the user experience by returning a more appropriate 400 Bad Request error for invalid page tokens.
This change introduces a new error type, ErrInvalidPageToken, in the adapter layer.
For the spanner adapter, when it receives the invalid cursor error, it will raise the ErrInvalidPageToken error. The server will then return a 400 error to the client.
This pattern is adopted for all endpoints that use page tokens.
=> Return 400 Bad Request for Invalid Page Tokens

backend/pkg/httpserver/get_feature.go, backend/pkg/httpserver/get_feature_test.go, backend/pkg/httpserver/get_features.go, backend/pkg/httpserver/get_features_test.go, backend/pkg/httpserver/get_saved_search.go, backend/pkg/httpserver/list_saved_searches.go, backend/pkg/httpserver/server.go, backend/pkg/httpserver/server_test.go, lib/gcpspanner/spanneradapters/backend.go, lib/gcpspanner/spanneradapters/backend_test.go, openapi/backend/openapi.yaml
This PR adds operation IDs to several routes in the OpenAPI specification that were previously missing them.
**Naming Conventions:**
* `list`: Used for operations that return an array of data.
* `get`: Used for operations that return a single entity.
These conventions are consistent with existing operation IDs in the specification.
**Benefits:**
Adding operation IDs makes the API specification more complete and easier to use with tools and libraries that rely on them.
Other changes:
- Metadata changes about the server and version (Because of #383).
=> Add Missing Operation IDs to OpenAPI Routes

lib/gcpspanner/searchtypes/features_search_parse_test.go, lib/gcpspanner/searchtypes/features_search_visitor.go
This commit contains changes to fix errors during the weekly review of the 500 errors.
This week:
- When a non date range is given for available_date, the node was nil (even though the type is not a pointer). When we tried to read GetText() of the node, it fails and returns a 500 error. This change does a nil check first.
=> Fix 500 error bugs - 2025-01-27

backend/pkg/httpserver/get_feature_metadata_test.go, backend/pkg/httpserver/get_feature_test.go, backend/pkg/httpserver/get_features_test.go, backend/pkg/httpserver/list_aggregated_feature_support_test.go, backend/pkg/httpserver/list_aggregated_wpt_metrics_test.go, backend/pkg/httpserver/list_chromium_usage_test.go, backend/pkg/httpserver/list_feature_wpt_metrics_test.go, backend/pkg/httpserver/list_missing_one_implementation_counts_test.go, backend/pkg/httpserver/server_test.go, openapi/backend/openapi.yaml
This PR improves the reliability and maintainability of our HTTP tests by transitioning from direct calls to the generated OpenAPI server methods to using the `httptest` package for true HTTP-level testing. 
**Motivation:**
Currently, our tests bypass the HTTP layer, which limits their ability to identify issues with request handling, middleware, and serialization. This refactor provides a more accurate representation of real-world scenarios and enables better testing of components like the upcoming auth middleware.
**Changes:**
* **`httptest` Integration:**  All HTTP handler tests now utilize `httptest` to simulate actual HTTP requests and responses. This involves updating test inputs to `*http.Request` and expected outputs to `*http.Response`.
* **Centralized Assertions:**  Common …
=> Refactor: Use httptest for HTTP layer testing

workflows/steps/services/chromium_histogram_enums/workflow/chromium_codesearch_enum_fetcher.go, workflows/steps/services/chromium_histogram_enums/workflow/chromium_codesearch_enum_fetcher_test.go
Background: https://github.com/GoogleChrome/chromium-dashboard/pull/4740
Dashboard reported a failure:
=> Fix enum URL for histograms

backend/pkg/httpserver/list_saved_searches.go, backend/pkg/httpserver/server.go, openapi/backend/openapi.yaml
This commit introduces new endpoints for managing saved searches and refines the existing saved searches API design for consistency and clarity.
To better organize the API, endpoints are grouped into two primary namespaces:
* `/v1/saved-searches`: This namespace focuses on the saved search resource itself and includes endpoints for creating (`POST`) and updating (`PATCH`) saved searches. This structure reflects that these actions operate directly on the saved search, regardless of ownership or user context.
* `/v1/users/me/saved-searches`: This namespace focuses on user-specific actions related to saved searches. It includes endpoints for listing saved searches (`GET`) and managing bookmarks (`GET`, `PUT`, `DELETE`). This grouping emphasizes the user's interaction with and management of …
=> feat: Add saved search endpoints and refine API design [1/4]

lib/auth/gcip_authenticator.go, lib/auth/gcip_authenticator_test.go, lib/auth/types.go, lib/go.mod, lib/go.sum, workflows/steps/services/uma_export/go.mod, workflows/steps/services/uma_export/go.sum
Background: In a future PR, we will introduce an authenticator http middleware that will call Authenticate.
This change is the Google Cloud Identity Platform (GCIP) implementation of that Authenticate interface.
GCIP uses firebase under the hood. This implementation comes straight from the admin SDK docs: https://firebase.google.com/docs/auth/admin/verify-id-tokens#go
This change also adds a new User type that the middleware will expect.
Other changes:
- Run go mod tidy on each package via `make go-tidy` - Needed after importing `firebaseauth.Token` into `lib`
This is a split up of #1118
=> feat: Add Google Cloud Identity Platform authenticator [2/4]

lib/httpmiddlewares/bearertokenauth.go, lib/httpmiddlewares/bearertokenauth_test.go
This middleware adds support for Bearer token authentication in your API. It extracts the Bearer token from the Authorization header and passes it to an `Authenticator` interface for verification. The implementation of the `Authenticator` interface is provided separately.
Key features
* Extracts Bearer token: The middleware extracts the Bearer token from the Authorization header if present.
* Passes token to authenticator: It passes the extracted token to an `Authenticator` interface, which is responsible for verifying the token and returning a user object if the authentication is successful.
* Handles missing or invalid tokens: The middleware handles cases where the Authorization header is missing or malformed by returning appropriate error responses.
* Customizable error responses: The …
=> feat: Add bearer token http middleware [3/4]

lib/gcpspanner/browser_feature_count.go, lib/gcpspanner/browser_feature_count_test.go, lib/gcpspanner/excluded_feature_keys.go, lib/gcpspanner/feature_search_test.go, lib/gcpspanner/missing_one_implementation.go, lib/gcpspanner/missing_one_implementation_test.go
Unlike feature-specific statistic Spanner calls, the aggregation calls (`ListBrowserFeatureCountMetric`, `ListMissingOneImplCounts`) account for all features but do not consider the `ExcludedFeatureKeys` table.
This table contains manually entered human-readable feature keys that should be excluded from the calculations.
This change addresses this by:
1. Retrieving the Spanner UUIDs for each feature key in the `ExcludedFeatureKeys` table.
2. Filtering out these excluded features during the count calculations in the `ListBrowserFeatureCountMetric` and `ListMissingOneImplCounts` functions.
This improvement ensures that the aggregation calls accurately reflect the desired feature counts by excluding manually specified features.
Note: There is one more aggregation call that needs this …
=> Factor in ExcludedFeatureKeys for aggregation calls

backend/pkg/httpserver/list_aggregated_baseline_status_counts.go, backend/pkg/httpserver/server_test.go, openapi/backend/openapi.yaml
Depends on #1132 
This PR updates the OpenAPI documentation to reflect the new /v1/stats/baseline_status/low_date_feature_counts endpoint.
This endpoint will return a paginated list of baseline status metrics, providing the count of features that have reached low baseline over time.
Next Steps:
- Implement the corresponding HTTP handler function to handle requests to this endpoint.
- Connect the handler function to the ListBaselineStatusCount Spanner logic implemented in the previous PR.
- Add appropriate error handling and logging to the handler.
This PR lays the groundwork for exposing the baseline status count functionality through the API.
=> feat: Expose ListBaselineStatusCount in OpenAPI spec

frontend/src/static/js/components/test/webstatus-overview-cells.test.ts, frontend/src/static/js/components/webstatus-overview-cells.ts, frontend/src/static/js/components/webstatus-overview-table.ts
This should resolve #1043.
Instead of disabling the sl-tooltop for unavailable features, the app will now display a tooltip that says "Not available".
=> Show "Not available" tooltip.

lib/gcpspanner/baseline_status_count.go, lib/gcpspanner/baseline_status_count_test.go
This is from today's discussion with @atopal. (There will be more parts to add the API and frontend parts into the global feature support chart)
This PR introduces the `ListBaselineStatusCounts` function and its associated helper functions to retrieve a cumulative count of baseline features over time.
The `ListBaselineStatusCounts` function works similarly to `ListBrowserFeatureCountMetric` by:
1. Calculating an initial cumulative count of baseline features up to the specified `startAt` date.
2. Retrieving subsequent baseline feature counts within the specified date range (`startAt` to `endAt`).
3. Accumulating these counts to provide a cumulative view of baseline feature adoption over time.
Currently, the function only supports retrieving counts based on the `LowDate` field in the …
=> feat: Add ListBaselineStatusCounts to retrieve cumulative baseline feature counts in spanner

lib/gcpspanner/spanneradapters/backend.go, lib/gcpspanner/spanneradapters/backend_test.go
Depends on #1132 
This is the adapter layer for ListBaselineStatusCounts between the http and spanner layers.
This is similar to ListMissingOneImplCounts (also used on the stats page)
=> Add spanner adapter layer for ListBaselineStatusCounts

backend/pkg/httpserver/list_aggregated_baseline_status_counts.go, backend/pkg/httpserver/list_aggregated_baseline_status_counts_test.go, backend/pkg/httpserver/server.go, backend/pkg/httpserver/server_test.go
This change adds the logic to call the spanner adapter layer for ListBaselineStatusCounts
This is similar to ListMissingOneImplCounts (also used on the stats page)
=> Add http logic for ListBaselineStatusCounts

Makefile, docs/testing.md, e2e/tests/feature-page.spec.ts, e2e/tests/overview-page.spec.ts, e2e/tests/utils.ts, playwright.config.ts
_tl;dr_: No more manually setting CI=true for playwright commands.
This came up again in the developer sync this week and has been going on for awhile
This pull request introduces two key changes to improve the reliability and efficiency of Playwright tests in local development:
1.  **Reduce Playwright Workers to 1:**
-  The number of Playwright workers has been consistently set to 1, regardless of the environment (local or CI).
-  This change addresses potential resource contention and instability that can occur with multiple workers, particularly in local development environments.
-  Consistently using one worker reduces the chance of flaky tests due to resource limitations.
2.  **Add `SKIP_FRESH_ENV=1` Option for Faster Local Iteration:**
-  A new `SKIP_FRESH_ENV=1` option has been …
=> Reduce Playwright Workers to 1 and Add SKIP_FRESH_ENV Option

frontend/src/static/js/components/test/webstatus-gchart.test.ts, frontend/src/static/js/components/webstatus-gchart.ts
This PR enhances the `webstatus-gchart` component by adding the ability to detect and dispatch events when data points on the chart are selected or deselected. This functionality enables parent components to react to user interactions with the chart and provide more context-specific information or actions.
**Key changes:**
* **`point-selected` and `point-deselected` events:** The component now dispatches these custom events when a data point is selected or deselected, respectively.
* **Event details:** The `point-selected` event provides details about the selected point, including the series `label`, `timestamp`, and `value`. The `point-deselected` event has no detail.
* **JSDoc updates:** The component's JSDoc comment is updated to include documentation for the new events.
This …
=> Enhance `webstatus-gchart` with point selection events

frontend/src/static/js/components/test/webstatus-line-chart-panel.test.ts, frontend/src/static/js/components/webstatus-line-chart-panel.ts
This will be useful for this milestone: https://github.com/GoogleChrome/webstatus.dev/milestone/10
This PR builds upon the enhanced `webstatus-gchart` component (see related PR #1177 ) by adding functionality to the `WebstatusLineChartPanel` abstract class to handle point selection and deselection events. This provides a consistent and customizable way for subclasses to react to user interactions with the chart.
**Key changes:**
* **`createPointSelectedTask` method:** This new method allows subclasses to define a `Task` to be executed when a point is selected on the chart. It also enables them to provide a `renderSuccess` function to render content based on the task's result.
* **Event handling:** The `handlePointSelected` and `handlePointDeselected` methods handle the `point-selected` …
=> Add point selection handling to `WebstatusLineChartPanel`

backend/pkg/httpserver/cache.go, backend/pkg/httpserver/cache_test.go
This pull request introduces the operationResponseCache utility, a generic caching mechanism designed to simplify the management of cached operation results. This is a foundational step towards enabling individual HTTP handlers to manage their own caching logic.
Changes:
operationResponseCache struct:
- A new operationResponseCache struct is introduced in pkg/httpserver/cache.go.
- It provides a consistent way to cache and retrieve operation results, using a RawBytesDataCacher (e.g., Valkey) as its underlying storage mechanism.
- The operationID acts as a prefix for all cache keys, allowing for logical grouping of cached data per operation. This also enables future batch operations, such as bulk deletion of cache entries by prefix.
- It handles json serialization and deserialization of …
=> Introduce operationResponseCache for Handler-Specific Caching

backend/pkg/httpserver/cache.go, backend/pkg/httpserver/get_feature_metadata_test.go, backend/pkg/httpserver/get_feature_test.go, backend/pkg/httpserver/get_features_test.go, backend/pkg/httpserver/list_aggregated_baseline_status_counts_test.go, backend/pkg/httpserver/list_aggregated_feature_support_test.go, backend/pkg/httpserver/list_aggregated_wpt_metrics_test.go, backend/pkg/httpserver/list_chromium_usage_test.go, backend/pkg/httpserver/list_feature_wpt_metrics_test.go, backend/pkg/httpserver/list_missing_one_implementation_counts_test.go, backend/pkg/httpserver/server.go, backend/pkg/httpserver/server_test.go
Summary:
The `operationResponseCaches` struct a provides a collection of type-safe caches that wrap around the raw bytes data cacher. `operationResponseCaches`` is integrated directly into the Server struct, providing easy access to all handlers. This PR also refactors the testing infrastructure to support future cache testing by renaming assertMockCallCount to assertMocksExpectations and allowing the passing in of a MockRawBytesDataCacher. We use the handler's request object (converted to JSON) as the key for the cache. 
The format of the key is `K_REVISION`-`OperationID`-`RequestDataInJSON`. The value type is the 2xx response object for that handler.
Changes:
operationResponseCaches Struct:
- A new operationResponseCaches struct is introduced in pkg/httpserver/cache.go.
- This struct …
=> Introduce `operationResponseCaches` struct

backend/pkg/httpserver/list_missing_one_implementation_counts.go, backend/pkg/httpserver/list_missing_one_implementation_counts_test.go
This pull request implements caching for the ListMissingOneImplemenationCounts API handler
=> Implement Caching for ListMissingOneImplemenationCounts

backend/pkg/httpserver/list_aggregated_wpt_metrics.go, backend/pkg/httpserver/list_aggregated_wpt_metrics_test.go
This pull request implements caching for the ListAggregatedWPTMetrics API handler
=> Implement Caching for ListAggregatedWPTMetrics

backend/pkg/httpserver/list_aggregated_baseline_status_counts.go, backend/pkg/httpserver/list_aggregated_baseline_status_counts_test.go
This pull request implements caching for the ListAggregatedFeatureSupport API handler
=> Implement Caching for ListAggregatedBaselineStatusCounts

antlr/FeatureSearch.g4, lib/gcpspanner/searchtypes/features_search_parse_test.go
This commit enhances the grammar to correctly parse names containing periods, such as `intl.segmenter`, within the ANY_VALUE rule.
Previously, the ANY_VALUE rule was too restrictive and did not allow for periods in unquoted values. This update modifies the rule to allow periods while still preventing it from incorrectly consuming the `..` used in date range queries.
With this change, the grammar now supports a wider range of valid input values, including names with periods.
=> Support names with periods in ANY_VALUE

infra/storage/spanner/migrations/000014.sql, lib/gcpspanner/feature_discouraged_details.go, lib/gcpspanner/feature_discouraged_details_test.go
This change adds a new table: FeatureDiscouragedDetails
It is setup to have a foreign key with its corresponding  Web Feature.
The other fields come from [web features](https://github.com/web-platform-dx/web-features/blob/1332db1a8ceb74af13fbcb58ee8501aa2b948f71/schemas/data.schema.json#L60-L81).
We don't plan on querying for individual details in AccordingTo and Alternatives. Those two fields are marked as nullable because we may get rid of them in the future.
=> Add table and logic to store discouraged details

lib/gcpspanner/baseline_status_count.go, lib/gcpspanner/baseline_status_count_test.go, lib/gcpspanner/browser_feature_count.go, lib/gcpspanner/browser_feature_count_test.go, lib/gcpspanner/client.go, lib/gcpspanner/feature_discouraged_details.go, lib/gcpspanner/feature_search_test.go, lib/gcpspanner/missing_one_implementation.go, lib/gcpspanner/missing_one_implementation_test.go
This change modifies all of the spanner calls used on the stats page.
It adds a new getAllDiscouragedFeatureIDs method which is similar to [getFeatureIDsForEachExcludedFeatureKey](https://github.com/GoogleChrome/webstatus.dev/blob/88b65fb0b5645ddc0b0b90ca46bfe9ab85e314db/lib/gcpspanner/excluded_feature_keys.go#L25-L52)
getFeatureIDsForEachExcludedFeatureKey and getAllDiscouragedFeatureIDs are both now called in a common method named getIgnoredFeatureIDsForStats that is used in each spanner query for the stats page.
This change comes from last week's feedback to ignore discouraged features.
Builds on #1211
=> Exclude discouraged features from spanner calls used on stats page

jsonschema/web-platform-dx_web-features/defs.schema.json, lib/gcpspanner/spanneradapters/web_features_consumer.go, lib/gcpspanner/spanneradapters/web_features_consumer_test.go
This change modifies the web features workflow to call the spanner logic that inserts discouraged details (if those details exist for a feature)
Other changes:
- Manually add missing data type to discouraged field: See https://github.com/web-platform-dx/web-features/pull/2697
Builds on #1211
=> Ingest discouraged details in web features job

frontend/src/static/js/components/test/webstatus-feature-usage-chart-panel.test.ts, frontend/src/static/js/components/test/webstatus-feature-wpt-progress-chart-panel.test.ts, frontend/src/static/js/components/test/webstatus-stats-global-feature-count-chart-panel.test.ts, frontend/src/static/js/components/test/webstatus-stats-missing-one-impl-chart-panel.test.ts, frontend/src/static/js/components/webstatus-feature-usage-chart-panel.ts, frontend/src/static/js/components/webstatus-feature-wpt-progress-chart-panel.ts, frontend/src/static/js/components/webstatus-line-chart-panel.ts, frontend/src/static/js/components/webstatus-stats-global-feature-count-chart-panel.ts, frontend/src/static/js/components/webstatus-stats-missing-one-impl-chart-panel.ts
These variables are used for the actual fetching of the data.
This will help us gather more data so that the lines don't end unexpectedly if there are no data points right at the beginning.
These variables are calculated during the willUpdate [callback](https://lit.dev/docs/components/properties/#:~:text=To%20compute%20values%20from%20existing%20properties%2C%20we%20recommend%20using%20the%20willUpdate%20callback%2C%20which%20allows%20you%20to%20set%20values)
They are calculated from dataFetchStartDateOffsetMsec and dataFetchEndDateOffsetMsec
Each data panel can override those values as needed. For example, the global feature chart on the stats page has dataFetchStartDateOffsetMsec set to 500 days because there's are two data points where there are >400 days in between them.
The default …
=> Add dataFetchStartDate and dataFetchEndDate variables

backend/pkg/httpserver/cache.go, backend/pkg/httpserver/list_missing_one_implementation_counts.go, backend/pkg/httpserver/list_missing_one_implementation_counts_test.go, backend/pkg/httpserver/server_test.go, frontend/src/static/js/components/test/webstatus-feature-page.test.ts, openapi/backend/openapi.yaml
Correct the typo `implemenation` to `implementaion` in MissingOneImplementationCounts
=> Correct implemenation to implementaion

workflows/steps/services/wpt_consumer/pkg/workflow/score_webfeature.go, workflows/steps/services/wpt_consumer/pkg/workflow/score_webfeature_test.go
This change is essentially a port of these two PRs:
- https://github.com/web-platform-tests/wpt.fyi/pull/4290
- https://github.com/web-platform-tests/wpt.fyi/pull/4294
Fixes #1106
The logic to increment TestPass comes from the earlier PRs. And missing tests should not increment subtest counts or TestPass count. It should only increment TotalTests by one for a given feature.
Other fixes:
- This also fixes a problem where crashed tests were being counted as passing. The unit test reduced the count for feature6.
- Skip counting subtests if the test file is missing.
=> Fix view=test scoring

frontend/src/static/js/components/test/webstatus-gchart.test.ts, frontend/src/static/js/components/webstatus-gchart.ts
When the gchart redraws (either from resizing the window or the parent encompassing component redraws it), it drops the selected data points.
This change fixes that.
This was originally reported in the description in #1242
=> Store and reuse selection in between draws

lib/gcpspanner/client.go, lib/gcpspanner/delete_user_saved_search.go, lib/gcpspanner/delete_user_saved_search_test.go, lib/gcpspanner/user_search_bookmarks.go
This change adds the logic to delete a single saved search.
This change adds removeUserSavedSearchMapper which implements the removableEntityMapper interface.
Prior the deletion, it does a role check for the user id.
Other changes:
- Slight changes to removableEntityMapper interface
Fixes #805
=> Spanner logic to delete a single user saved search

frontend/src/static/js/api/client.ts, frontend/src/static/js/components/test/webstatus-stats-missing-one-impl-chart-panel.test.ts, frontend/src/static/js/components/webstatus-line-chart-panel.ts, frontend/src/static/js/components/webstatus-stats-missing-one-impl-chart-panel.ts
#1111. Create a table to display missing feature IDs after a point is selected. The table displays `ceil(missing_features_length/10) ` columns and 10 rows each, to adapt this content for better horizontal display.
The maximum number of  missing features on the graph is 76.
=> Show missing features specifically for each data point

backend/pkg/httpserver/create_saved_search.go, backend/pkg/httpserver/create_saved_search_test.go, backend/pkg/httpserver/middlewares_test.go, backend/pkg/httpserver/server.go, backend/pkg/httpserver/server_test.go, openapi/backend/openapi.yaml
This change implements the http handler for creating a user saved search.
Prior to calling the adapter layer (which is implemented in #1245), we:
- Get the user from the context (which should be at this point)
- Validate the input
- If the input is invalid, return ExtendedErrorModel which has the fields with problems
- Calls the adapter layer to create the saved search.
Other changes:
- Slight changes to ExtendedErrorModel
- Make the create saved search endpoint's 400 error use ExtendedErrorModel (the first endpoint to use ExtendedErrorModel)
- Add some max length limits to input fields
=> HTTP Server: create user saved search

lib/gcpspanner/client.go, lib/gcpspanner/delete_user_saved_search.go, lib/gcpspanner/delete_user_saved_search_test.go, lib/gcpspanner/spanneradapters/backend.go, lib/gcpspanner/spanneradapters/backend_test.go, lib/gcpspanner/spanneradapters/backendtypes/types.go
This is the layer between the httpserver and spanner.
It parses out the error if the:
- The user does not have access, or
- The entity does not exist
Other changes
- Modify the spanner logic to check if the entity exists in the same transaction
=> Add adapter logic that calls spanner to delete user saved search

backend/pkg/httpserver/remove_saved_search.go, backend/pkg/httpserver/remove_saved_search_test.go, backend/pkg/httpserver/server.go, backend/pkg/httpserver/server_test.go, openapi/backend/openapi.yaml
This change implements the http handler for removing a user saved search.
After calling the adapter layer (which is implemented in #1264), we:
- Check the error type to distinguish between:
- A missing saved search
- A saved search that the user does not have access to delete
- A generic error
Other changes:
- Modify the test helper when comparing No content responses.
=> HTTP Server: remove user saved search

lib/gcpspanner/missing_one_implementation_feature_list.go, lib/gcpspanner/missing_one_implementation_feature_list_test.go, lib/gcpspanner/missing_one_implementation_test.go
A part of #1109. Implementing the Spanner logic to retrieve the list of feature IDs that are counted as "missing one implementation" for a target browser and target date. 
This change is similar to the implementation in https://github.com/GoogleChrome/webstatus.dev/blob/main/lib/gcpspanner/missing_one_implementation.go#L197, but with a simpler template. Unlike that implementation, both GCP and local emulator use the same template.
A simpler version is tested on the [Spanner studio](https://pantheon.corp.google.com/spanner/instances/staging-spanner/databases/staging-database/details/query?inv=1&invt=Abrs3g&project=webstatus-dev-internal-staging)
Handle potential exclusions specified in the ExcludedFeatureKeys table.
support pagination to handle potentially large numbers of feature IDs.
=> Spanner query for missing one implementation feature IDs 

lib/gcpspanner/missing_one_implementation_feature_list.go, lib/gcpspanner/missing_one_implementation_feature_list_test.go
#1109. Support pagination to handle potentially large numbers of feature IDs. Implement the cursor through an `Offset`  from the start of the result set.
=> Support pagination for missing one implementation feature IDs query

lib/gcpspanner/missing_one_implementation_feature_list.go, lib/gcpspanner/missing_one_implementation_feature_list_test.go
Fix #1109. Handle exclusions specified in the `FeatureDiscouragedDetails` and `ExcludedFeatureKeys` table
=> Handle exclusions specified in the ExcludedFeatureKeys table

frontend/src/static/js/components/webstatus-overview-filters.ts, frontend/src/static/js/utils/app-router.ts
Hi @jcscottiii, this is a enhancement, addressing the issue: https://github.com/GoogleChrome/webstatus.dev/issues/1237
I am also working to immediately reflect the disabled state(low opacity and hover disable) of `search Icon`, will be able to make a PR on i soon, also can I do draft PR and ask for assistance?
=> Prevent page refresh if present result is same as result to be searched

lib/gcpspanner/spanneradapters/backend.go, lib/gcpspanner/spanneradapters/backend_test.go
This will be used by the [getSavedSearch](https://github.com/GoogleChrome/webstatus.dev/blob/078beb7fecb7c22cdd3eb2dbd3c814eb2e84beb9/openapi/backend/openapi.yaml#L783) http handler
This is the layer between the httpserver and spanner.
It parses out the error if it is:
- The `entity does not exist` error, or
- General error
=> Add adapter logic for GetSavedSearch

backend/pkg/httpserver/get_saved_search.go, backend/pkg/httpserver/get_saved_search_test.go, backend/pkg/httpserver/server.go, backend/pkg/httpserver/server_test.go
This calls the adapter code to get a saved search.
It allows for both unauthenticated and authenticated requests
If the call is authenticated, it gets extra information for the saved search regarding the relationship of the user to the saved search
=> Add the server code to get saved searches

lib/gcpspanner/list_user_saved_searches.go, lib/gcpspanner/list_user_saved_searches_test.go
Implements Spanner logic for the `/v1/users/me/saved-searches` (listUserSavedSearches) endpoint, retrieving paginated bookmarked searches for an authenticated user.
* This method is called with the authenticated user's ID.
* It returns only bookmarked saved searches.
As a reminder: a user can bookmark a saved search by:
1.  Creating a saved search. This automatically bookmarks it for the owner (similar to [Issue Tracker hotlists](https://developers.google.com/issue-tracker/guides/work-with-hotlist#:~:text=Note%3A%20Hotlists%20that%20you%20own%20are%20starred%20automatically.)).
2.  Bookmarking others' saved searches (read-only).
=> Add Spanner logic for paginated bookmarked searches

lib/gcpspanner/missing_one_implementation_feature_list.go, lib/gcpspanner/missing_one_implementation_feature_list_test.go
Fix the nil pointer issue when a token is empty and the cursor is nil. It causes a `invalid memory address or nil pointer dereference` in staging testing
=> Add an empty token check in missing_one_implementation_feature_list

frontend/src/static/js/components/test/webstatus-stats-missing-one-impl-chart-panel.test.ts, frontend/src/static/js/components/webstatus-stats-missing-one-impl-chart-panel.ts
A follow-up request for #1111. Add an anchor link to overview page that shows the same set of feature IDs in MissingOneImplementationFeatureList.
Staging testing note:
Test it with max numbers of feature list, 80~
=> Add anchor link to overview page with feature ID list

frontend/src/static/js/components/test/webstatus-stats-missing-one-impl-chart-panel.test.ts, frontend/src/static/js/components/webstatus-stats-missing-one-impl-chart-panel.ts
Fix #1301. A list of UI adjustments:
- Make the header more distinguishable, with a new format of `Missing only in Chrome on 2023-12-10: <a ..>12 features</a>`
- Add 1em padding-right for the text contentinside of the table
- Use browser labels for the header, mentioned [here](https://github.com/GoogleChrome/webstatus.dev/pull/1298#issuecomment-2741276226)
=> UI adjustments for MissingOneImplFeatureList

.golangci.yaml, Makefile, lib/gcpspanner/browser_feature_support_event.go, lib/gcpspanner/feature_search_query.go, util/cmd/load_fake_data/main.go, workflows/steps/services/bcd_consumer/pkg/data/parser_test.go, workflows/steps/services/bcd_consumer/pkg/workflow/bcd_filter_data.go, workflows/steps/services/common/repo_downloader/pkg/gh/download.go
Fixes: #1316
Our CI process installs the latest golangci-lint. And they just released a new major version.
Luckily, they have a migrate guide and command. The command auto generated the changes to .golangci.yaml. No manual changes to .golangci.yaml were made (Except running make license-fix).
The rest of the changes fix the issues found in #1316
=> chore: Fix golangci-lint upgrade

frontend/src/static/js/components/test/webstatus-stats-missing-one-impl-chart-panel.test.ts, frontend/src/static/js/components/webstatus-stats-missing-one-impl-chart-panel.ts
Address comments in https://github.com/GoogleChrome/webstatus.dev/pull/1298#discussion_r2004559219.  This PR removes the `target="_blank` and keep the navigation within the tab.
=> Keep navigation within the tab in MissOneImpl Chart

frontend/src/static/js/components/test/webstatus-overview-content.test.ts, frontend/src/static/js/components/test/webstatus-sidebar-menu.test.ts, frontend/src/static/js/components/webstatus-overview-content.ts, frontend/src/static/js/components/webstatus-services-container.ts, frontend/src/static/js/components/webstatus-sidebar-menu.ts, frontend/src/static/js/contexts/app-bookmark-info-context.ts, frontend/src/static/js/services/test/webstatus-bookmarks-service.test.ts, frontend/src/static/js/services/webstatus-bookmarks-service.ts, frontend/src/static/js/utils/app-router.ts
Currently, the code relies on the `DEFAULT_BOOKMARKS` constant to get the current list of bookmarks.
However, this leads to a problem where we can't have a dynamic list of bookmarks.
This is a refactoring that moves that information to a central location: webstatus-bookmarks-service.
Any child component can subscribe to that context to get updates.
Then in the future, we can have a process that can update the bookmark info.
Also there were multiple components figuring out the current bookmark. The service figures it out and publishes that information too.
This refactor is part of the changes needed for Saved Searches (in which some bookmarks will be coming from the server.)
=> refactor: Add bookmarks context

frontend/src/static/js/components/test/webstatus-overview-table.test.ts, frontend/src/static/js/components/webstatus-overview-content.ts, frontend/src/static/js/components/webstatus-overview-page.ts, frontend/src/static/js/components/webstatus-overview-table.ts, frontend/src/static/js/utils/task-tracker.ts
Right now, the task tracker uses null for missing values. We should instead use undefined.
=> refactor: use undefined instead of null for TaskTracker

frontend/src/static/js/utils/test/urls.test.ts, frontend/src/static/js/utils/urls.ts
Also modify getContextualQueryStringParams so that users are able to send saved searches urls by setting search_id in the query parameter
=> Add url helper for search_id for saved searches

lib/gcpspanner/browser_availabilities.go, lib/gcpspanner/browser_availabilities_test.go, lib/gcpspanner/browser_feature_count_test.go, lib/gcpspanner/browser_feature_support_event_test.go, lib/gcpspanner/client.go, lib/gcpspanner/feature_search_test.go, lib/gcpspanner/missing_one_implementation_feature_list_test.go, lib/gcpspanner/missing_one_implementation_test.go, lib/gcpspanner/spanneradapters/web_features_consumer.go, lib/gcpspanner/spanneradapters/web_features_consumer_test.go, util/cmd/load_fake_data/main.go
Modified InsertBrowserFeatureAvailability to UpsertBrowserFeatureAvailability to support updates.
To support this, I added a new entityUniqueWriter struct for this. Take a look at the constraint info section for more information as to why.
Due to the unique index on `(WebFeatureID, BrowserName)` in the `BrowserFeatureAvailabilities` table, updates are handled via a "delete then insert" pattern. The `entityUniqueWriter` is used to implement this behavior.
We were able to use most of the existing mapper functionality when using the entityUniqueWriter. I got rid of the Merge method because we aren't really doing merges in this case. And I also implemented the DeleteKey method to extract the keys to delete the row before inserting the new one.
=> Allow Updates of Browser Feature Availabilities

frontend/src/static/js/components/test/webstatus-stats-missing-one-impl-chart-panel.test.ts, frontend/src/static/js/components/webstatus-stats-missing-one-impl-chart-panel.ts
Fix #1322. Use `<h3>` for header and add 1em margin to the bottom.
=> Adjust header size and margin in MissOneImplf feature list

frontend/src/static/js/api/client.ts, frontend/src/static/js/components/webstatus-overview-content.ts, frontend/src/static/js/components/webstatus-sidebar-menu.ts, frontend/src/static/js/contexts/app-bookmark-info-context.ts, frontend/src/static/js/contexts/test/app-bookmark-info-context.test.ts, frontend/src/static/js/utils/constants.ts, frontend/web-test-runner.config.mjs
Why: This is the pre-work for the changes to come to frontend/src/static/js/services/webstatus-bookmarks-service.ts for loading a saved search id from the query parameter.
This change adds two new fields to the context:
- userSavedSearchBookmarkTask: TaskTracker with information about the optional saved search bookmark being loaded when search_id query parameter is provided.
- currentLocation: A snapshot of the location information that applies to the info in the context. We will use this to let us know if our data is outdated.
This change also reorganizes the existing helpers into `bookmarkHelpers`. This will be useful for stubing. Because previously, we would run into this [issue](https://sinonjs.org/how-to/stub-dependency/)
There are two new helpers added:
- getCurrentQuery: A useful …
=> Add user saved bookmark info to app-bookmark-info-context

frontend/src/static/js/services/test/webstatus-bookmarks-service.test.ts, frontend/src/static/js/services/webstatus-bookmarks-service.ts, frontend/src/static/js/utils/app-router.ts
Depends on #1327 
Modified the WebstatusBookmarksService to have a new task loadingUserSavedBookmarkByIDTask. This task is automatically triggered by changes to the location, api client and user (for sign in and sign out so that we can get role information too when calling getSavedSearchByID by providing a token)
Upon completion it updates _userSavedBookmarkByIDTaskTracker (which is used in refreshAppBookmarkInfo like the other internal properties).
If it errors, it will show a toast using the custom error messages from #1327 as well as update the page url to remove the faulty search_id
Other changes:
- Renamed changedLocation to _changedLocation to be consistent with the other internal properties
- Add pathname to AppLocation because it is needed by updatePageUrl
=> Add task that automatically loads a search bookmark when search_id is present

e2e/tests/overview-page.spec.ts, frontend/src/static/js/components/test/webstatus-overview-filters.test.ts, frontend/src/static/js/components/webstatus-overview-filters.ts, frontend/src/static/js/components/webstatus-overview-page.ts, frontend/src/static/js/utils/task-tracker.ts
Depends on #1328 
This change subscribes various overview page components to appBookmarkInfoContext so that it can get bookmark info.
I also introduced a new Error for TaskTracker: TaskNotReadyError We need this error so that the call to getFeatures waits until we have gotten the information from user saved searches API.
You will see the changes in webstatus-overview-page.ts that use that new error.
Future PR TODO:
- When it comes to editing and creating these bookmarks, we will probably move around some of these components (Which might simplify the number of components subscribed to appBookmarkInfoContext). In the meantime, I did not add too many unit tests but instead added some e2e tests in playwright to help give some coverage. The playwright tests use the fake data populated …
=> Allow overview-page components to use appBookmarkInfoContext to automatically load public user saved searches

frontend/src/static/js/components/webstatus-login.ts, frontend/src/static/js/components/webstatus-overview-page.ts, frontend/src/static/js/contexts/app-bookmark-info-context.ts, frontend/src/static/js/contexts/firebase-user-context.ts, frontend/src/static/js/contexts/test/app-bookmark-info-context.test.ts, frontend/src/static/js/services/test/webstatus-bookmarks-service.test.ts, frontend/src/static/js/services/test/webstatus-firebase-auth-service.test.ts, frontend/src/static/js/services/webstatus-bookmarks-service.ts, frontend/src/static/js/services/webstatus-firebase-auth-service.ts, frontend/src/static/js/utils/task-tracker.ts, frontend/src/static/js/utils/urls.ts
Background:
This PR refactors data fetching in two components by disabling `autoRun` for Lit Tasks. An issue was observed in Firefox in PR #1330 where tasks were being triggered multiple times. The previous error handling using `TaskNotReadyError` and checks for duplicate tasks was insufficient. Lit Task aborts a currently pending task if a new one is triggered. This led to scenarios in Firefox where the initial task could be aborted, and subsequent tasks might return errors, preventing successful data retrieval.
This tries to simplify things by turning off autoRun and leveraging the willUpdate lit lifecycle method to precisely run a task. This also allows us to not have to do checks on the task's arguments within the task itself since we control when the task exactly triggers.
Main …
=> Refactor: Precise control over data fetching and task execution

frontend/src/static/js/api/client.ts, frontend/src/static/js/contexts/app-bookmark-info-context.ts, frontend/src/static/js/contexts/test/app-bookmark-info-context.test.ts, frontend/src/static/js/services/test/webstatus-bookmarks-service.test.ts, frontend/src/static/js/services/webstatus-bookmarks-service.ts, frontend/web-test-runner.config.mjs
This PR adds a new task in the frontend to support loading a user's saved bookmarks. This is the pre-req step for displaying these bookmarks in the sidebar (next PR).
Main changes:
- **`app-bookmark-info-context`:**
- Added a new `TaskTracker` property, `userSavedSearchBookmarksTask`, to the `AppBookmarkInfo` interface. This will hold the status and data of the user's bookmarks loading task.
- Updated the `isBusyLoadingBookmarkInfo` helper to consider the loading state of the `userSavedSearchBookmarksTask`.
- Introduced new error classes: `UserSavedSearchesInternalError` and `UserSavedSearchesUnknownError` to handle errors specific to fetching the user's bookmark list.
- **`webstatus-bookmarks-service`:**
- Added a new `loadingUserSavedBookmarksTask` (Lit Task) to fetch all of the current …
=> Add service for loading user bookmarks

backend/pkg/httpserver/server.go, lib/gcpspanner/spanneradapters/backend.go, lib/gcpspanner/spanneradapters/backend_test.go, openapi/backend/openapi.yaml
Also updated the openapi document to follow AIP-134 for this PATCH method https://google.aip.dev/134
This means adding an update_mask to the request.
This allows us to selectively update each field.
The adapter logic looks at the update_mask and converts it to the Optionally type in the gcpspanner layer
The validation of the request will happen in the http layer which will happen in the next PR.
=> Add adapter logic to update saved search

backend/pkg/httpserver/create_saved_search.go, backend/pkg/httpserver/create_saved_search_test.go, backend/pkg/httpserver/server.go, backend/pkg/httpserver/server_test.go, backend/pkg/httpserver/update_saved_search.go, backend/pkg/httpserver/update_saved_search_test.go, openapi/backend/openapi.yaml
This adds the HTTP layer for the update saved search operation.
Validation changes:
- Refactor the validation logic of SavedSearches so that CreateSavedSearch and UpdateSavedSearch
can both use the same logic.
- The update saved search validation contains additional checks for the update_mask passed in.
Other changes:
- Add 404 case for update saved search in the openapi document
=> HTTP Layer for Update Saved Search

lib/gcpspanner/client.go, lib/gcpspanner/user_search_bookmarks.go, lib/gcpspanner/user_search_bookmarks_test.go
We already have a limit for the number of saved searches a user can own.
This code adds a new configuration for the number of bookmarks they can have.
In addition to the 25 saved searches they can own, they also can bookmark 25 other saved searches that they don't own.
When a user creates a saved search, they are automatically bookmarked (Similar to [issue tracker](https://developers.google.com/issue-tracker/guides/work-with-hotlist#:~:text=Hotlists%20that%20you%20own%20are%20starred%20automatically)).
And in Issue Tracker, you can't remove the star if you are the admin. This change adds the same type of check.
=> Add checks for the number of bookmarks and prevent removal of owned searches

backend/pkg/httpserver/server.go, backend/pkg/httpserver/server_test.go, frontend/src/static/js/api/client.ts, openapi/backend/openapi.yaml
Change 1:
- This change adds the rest of the client code to call the remaining openapi methods for saved searches and bookmarks.
- You will see that for the update saved search, it handles the update mask and allows the description to be set to null which will clear it out
Change 2:
- Remove the extra route to get the bookmark status. Instead, the user will use the existing getSavedSearch/listUserSavedSearches (while authenticated) which will contain the user's bookmark status. When we list out the bookmarks for the side bar, we already have the status in that response. No need to get it again.
Change 3:
- Remove the response body for the 200 response for the put request for bookmark status since the user will be getting that from the getSavedSearch/listUserSavedSearches operations
=> Add missing frontend client code & remove extra route

lib/gcpspanner/spanneradapters/backend.go, lib/gcpspanner/spanneradapters/backend_test.go, lib/gcpspanner/spanneradapters/backendtypes/types.go
This change adds the adapter logic for the [putUserSavedSearchBookmark](https://github.com/GoogleChrome/webstatus.dev/blob/80e7bccea843ad8d02dd9a662c89143d650c06a8/openapi/backend/openapi.yaml#L656) and [removeUserSavedSearchBookmark](https://github.com/GoogleChrome/webstatus.dev/blob/80e7bccea843ad8d02dd9a662c89143d650c06a8/openapi/backend/openapi.yaml#L696) operations.
PutUserSavedSearchBookmark handles converting the errors from spanner for 1) bookmark limit exceeded and 2) entity does not exist to errors that the http layer will use to return the appropriate status code
RemoveUserSavedSearchBookmark handles converting the errors from spanner for 1) saved search owner cannot delete bookmark and 2) entity does not exist to errors that the http layer will use to return the appropriate …
=> Add adapter logic to handle bookmark operations

e2e/tests/overview-page.spec.ts, frontend/src/static/js/api/client.ts, util/cmd/load_test_users/main.go
The new `list user saved searches` returns no `data` field in the page if there is none. That list method uses a helper method that does the iteration for us. But previous routes always had a data field in the object
A logged in user will get this error in the console:
```
TypeError: a.data is not iterable (cannot read property undefined)
```
As well as see a toast like this:
This solves that
---
Long term, we should decide if we should provide the data field for all paginated routes. Even if  there is no data.
=> Bug Fix: handle non existent data field in paginated data

.golangci.yaml, backend/cmd/server/main.go, backend/pkg/httpserver/middlewares.go, backend/pkg/httpserver/middlewares_test.go, backend/pkg/httpserver/put_user_saved_search_bookmark.go, backend/pkg/httpserver/put_user_saved_search_bookmark_test.go, backend/pkg/httpserver/remove_user_saved_search_bookmark.go, backend/pkg/httpserver/remove_user_saved_search_bookmark_test.go, backend/pkg/httpserver/server.go, backend/pkg/httpserver/server_test.go
This change adds the HTTP layer logic for the [putUserSavedSearchBookmark](https://github.com/GoogleChrome/webstatus.dev/blob/80e7bccea843ad8d02dd9a662c89143d650c06a8/openapi/backend/openapi.yaml#L656) and [removeUserSavedSearchBookmark](https://github.com/GoogleChrome/webstatus.dev/blob/80e7bccea843ad8d02dd9a662c89143d650c06a8/openapi/backend/openapi.yaml#L696) operations.
Other changes:
I started to get duplicate code lint errors for these two operations. So I:
- Increased the threshold by a little bit.
- Refactored some of the duplicate user checking into a common CheckAuthenticatedUser method
- Reduced some duplicate test boilerplate code
- Introduced a common basicHTTPTestCase struct that we can probably use for most cases.
- Add other common helpers like createEmptyBodyResponse …
=> Add HTTP layer logic to handle bookmark operations

infra/backend/service.tf
Previously, it was set to [databaseReader](https://cloud.google.com/spanner/docs/iam#spanner.databaseReader). This change sets it to [databaseUser](https://cloud.google.com/spanner/docs/iam#spanner.databaseUser).
In the future, we should explore [fine grained access](https://cloud.google.com/spanner/docs/fgac-about) for per table access.
This is needed for the user saved searches work so the backend machine user can write to the database.
=> Adjust backend permissions for spanner

backend/cmd/server/main.go
This is needed by [this](https://github.com/GoogleChrome/webstatus.dev/blob/497c3bacf20ffe44b28da835217ec3eba48573cf/openapi/backend/openapi.yaml#L684-L695)
Split up of #1364
=> Add POST as an allowed method to CORS policy

frontend/src/static/js/components/test/webstatus-overview-content.test.ts, frontend/src/static/js/components/webstatus-overview-content.ts, frontend/src/static/js/components/webstatus-overview-filters.ts, frontend/src/static/js/components/webstatus-overview-page.ts, frontend/src/static/js/components/webstatus-typeahead.ts, frontend/src/static/js/utils/constants.ts
This change is a small refactor to a few small parts I saw while doing #1364
1. Move the vocabulary to the constants file.
- In the future, it will be used in other places, so I moved it to the constants file
2. Adding some types so we don't have to do type assertions
- It also points out that the ref can be of type `T | undefined`. For now, assume that it is always defined like before. We can revisit later if needed.
3. Previously, multiple components were subscribed to the appBookmarkInfo context. But really, we could just have one component subscribe and pass it down. That's what that change does.
=> Refactor: move vocab, adding types, simplify appBookmarkInfo usage

openapi/backend/openapi.yaml
This change adds the bearerAuth security requirement to the bookmark endpoints. Other endpoints have it but I missed these two. Without this change, those endpoints will get a 500 response code because it could not find the security requirement.
This comes from the split up of #1364
=> fixup: Add missing bearerAuth security requirement for bookmark endpoints

frontend/src/static/js/components/test/webstatus-overview-content.test.ts, frontend/src/static/js/components/test/webstatus-overview-filters.test.ts, frontend/src/static/js/components/test/webstatus-overview-table.test.ts, frontend/src/static/js/components/test/webstatus-sidebar-menu.test.ts, frontend/src/static/js/components/webstatus-overview-cells.ts, frontend/src/static/js/components/webstatus-overview-content.ts, frontend/src/static/js/components/webstatus-overview-filters.ts, frontend/src/static/js/components/webstatus-overview-page.ts, frontend/src/static/js/components/webstatus-overview-table.ts, frontend/src/static/js/components/webstatus-sidebar-menu.ts, frontend/src/static/js/contexts/app-bookmark-info-context.ts, frontend/src/static/js/contexts/test/app-bookmark-info-context.test.ts, frontend/src/static/js/services/test/webstatus-bookmarks-service.test.ts, frontend/src/static/js/services/webstatus-bookmarks-service.ts, frontend/src/static/js/utils/constants.ts, frontend/src/static/js/utils/test/urls.test.ts, frontend/src/static/js/utils/urls.ts
Previously, we used the phrases `bookmark` and `saved search` interchangeably. However, after creating the APIs, `saved searches` are the saved query objects and `bookmarks` describe a user's specific status related to a saved search.
This commit starts to rename a lot of the references to `bookmark` to `saved search`. We still need to rename the appBookmarkInfo to appSavedSearchInfo (since it's all about reading from the saved searches API), but that can come later (much later, this is just enough so that the UserSavedSearches functionality can land).
Besides the renaming mentioned above, there  are two new things:
`CurrentSavedSearch` is a new interface that can hold either one of the new interfaces: `UserSavedSearch` and `GlobalSavedSearch` This is done through a discriminated …
=> refactor: begin renaming bookmark to saved searches

frontend/src/static/js/components/test/webstatus-saved-search-controls.test.ts, frontend/src/static/js/components/webstatus-saved-search-controls.ts, frontend/src/static/js/utils/urls.ts
This component will be entrypoint to controlling saved searches and bookmark status on the overview page.
For creating/updating/deleting saved searches, this component will open the saved search editor component created in #1411
For bookmarking/unbookmarking, the controls component itself will handle the HTTP tasks to toggle the status. This component will dispatch either `saved-search-bookmarked` or `saved-search-unbookmarked` which will be handled by webstatus-bookmarks-service
=> Add saved search controls component

frontend/package.json, frontend/web-test-runner.config.mjs
Previously, while running web test runner, it could not find the source code.
As a result, a developer could not insert break points.
This fixes that.
=> Improve unit test ability for frontend code

Makefile
This will lower the risk of the call timing out.
=> Query for only one feature for port-forward-manual

frontend/src/static/js/components/test/webstatus-stats-missing-one-impl-chart-panel.test.ts, frontend/src/static/js/components/webstatus-overview-data-loader.ts, frontend/src/static/js/components/webstatus-overview-table.ts, frontend/src/static/js/components/webstatus-stats-missing-one-impl-chart-panel.ts, frontend/src/static/js/utils/constants.ts
This change updates the table displayed in the "Missing one" chart to use the existing `webstatus-overview-table` component.
=> Utilize overview table in "Missing One" panel

frontend/src/static/js/components/webstatus-stats-missing-one-impl-chart-panel.ts
Fixes #1471 
The "Chrome/Edge" label was not being effectively translated back to the BrowsersParameter version.
=> Fix Chrome/Edge missing features table bug

frontend/src/static/js/components/test/webstatus-stats-missing-one-impl-chart-panel.test.ts, frontend/src/static/js/components/webstatus-stats-missing-one-impl-chart-panel.ts
Per discussions, this is a basic change to the text displayed on the missing one table.
=> Clarify table text

.dev/auth/manifests/pod.yaml, .dev/datastore/manifests/pod.yaml, .dev/spanner/manifests/pod.yaml, .dev/valkey/manifests/pod.yaml, .devcontainer/Dockerfile, Makefile, backend/manifests/pod.yaml, docs/testing.md, e2e/tests/utils.ts, frontend/manifests/pod.yaml
During the saved search playwright tests, we kill and reopen the ports needed for the database (as well as all other ports).
We do this because beforehand, we did not port forward the ports for the database and only forwarded the ports needed to connect to the app (the backend already had access to the database internally)
But instead of doing that, we now port forward the database ports during `make port-forward-manual`. To help with that, I modified the helper makefile target to check if the port is live.  We use `nc` instead of curl because it did not work with grpc (which the spanner emulator uses). The devcontainer Dockerfile has been updated to install that dependency (devs will need to rebuild their devcontainer)
I also started to add readinessProbes for some of the pods. And for …
=> Fix playwright test flakiness

.golangci.yaml, lib/gcpspanner/spanneradapters/chromium_historgram_enum_consumer_test.go, lib/gcpspanner/spanneradapters/wptconsumertypes/types.go, lib/wptfyi/client.go, lib/wptfyi/client_integration_test.go, workflows/steps/services/chromium_histogram_enums/workflow/job_processor_test.go, workflows/steps/services/wpt_consumer/cmd/job/main.go
Currently, the wpt consumer job is failing [logs](https://cloudlogging.app.goo.gl/Cqax2o5RFX342mXr7).
The reason why it is failing comes from a few reasons:
- We are using the imported Go code from wpt.fyi incorrectly. It causes the formed URL to be wrong and cause 404.
- No `safari_ios` product exists in the product spec [code](https://github.com/web-platform-tests/wpt.fyi/blob/da8187c63fe9ac7e6dddb9137db5657063e32f74/shared/product_spec.go#L71-L110)
This change addresses those. In particular, I removed safari_ios for now because the wpt.fyi API results in an 400 error.  We can re-add it then. Also, the wpt.fyi api returns 404 when there's no available information for an actual product so I added a special case to check for that.
Additionally, I reconfigured the linter to also check for …
=> bugfix: Fix wptconsumer

lib/gcpspanner/browser_feature_support_event.go, lib/gcpspanner/spanneradapters/chromium_historgram_enum_consumer.go, lib/gcpspanner/spanneradapters/chromium_historgram_enum_consumer_test.go, lib/gcpspanner/web_features.go, lib/gcpspanner/web_features_test.go, lib/go.mod
The instructions in the mojom file[[1]](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/mojom/use_counter/metrics/webdx_feature.mojom;l=35-47;drc=822a70f9ac61a75babe9d24ddfc32ab475acc7e1) were updated to reflect how feature developers should translate feature IDs found in the web features repo to enum labels in the mojom file by doing the equivalent of `id.title().replace("-", "")`
However, our code takes the enum labels and tries to map convert labels to feature IDs.
Unfortunately, there's too much data loss to reliably convert back to the feature ID.
Examples:
* **Case 1: `http3` (WebDX ID) -> `Http3` (Enum Label)** The original ID `http3` has **no hyphen** between the letter 'p' and the digit '3'. A reverse algorithm designed to insert hyphens (e.g., …
=> bugfix: Fix mapping of enums to feature IDs

Makefile, package-lock.json
Seems like the combination of multiple dependabot changes left package-lock.json with unstaged changes again.
This changes adds those.
Also, added a Makefile target to detect them called `unstaged-changes`. This target is used in the precommit target so we should catch this in the future as the dependabot PRs are merged into main.
=> chore: add unstaged changes; detect unstaged changes

infra/.terraform.lock.hcl, infra/storage/outputs.tf, infra/storage/providers.tf, infra/storage/valkey.tf
There was a recent change that causes valkey to recreate the instance. By default, terraform will terminate the instance (10-15 mins) before creating it (10-15 minutes).
When I deployed this week's release to staging #1575 , it was discovered that the app hangs while still trying to connect to valkey and it messes up the response time during the full 30 minutes of waiting.
This change minimizes valkey downtime by creating the new instance before terminating the old one. To do this, we have to add some random characters to the end of the name since there can only be one instance with a given name per GCP project. Terraform will generate a new random string the next time it has to create it. Now, there should be minimal performance degradation since the new instance is active and ready …
=> Minimize valkey downtime by creating the new instance first

.devcontainer/post_create.sh, Makefile, images/nodejs_service.Dockerfile
This should also prevent unexpected changes to package-lock.json.
`npm ci` installs exactly what is in the lock file. npm install may update things if the dependency is prefixed with `^`
=> chore: Use npm ci instead of npm install

infra/storage/spanner/migrations/000018.sql, lib/gcpspanner/feature_group_lookups.go, lib/gcpspanner/feature_group_lookups_test.go, lib/gcpspanner/groups.go, lib/gcpspanner/web_features.go
This change is a split up of #1630. Check that description for the high level reason.
This particular change is the first part where we add a new table that contains the data.
The spanner method `UpsertFeatureGroupLookups` contains the logic to gather all the data and populate the table.
Notes about the table:
- I added a `Depth` column to enable future use cases in case users want to know only the features at a given level and not all the features for children groups.
=> feat: add FeatureGroupKeysLookup table for better feature search perf [Pt 1/3]

lib/gcpspanner/spanneradapters/web_feature_groups_consumer.go, lib/gcpspanner/spanneradapters/web_feature_groups_consumer_test.go, workflows/steps/services/web_feature_consumer/pkg/workflow/web_features_worker.go, workflows/steps/services/web_feature_consumer/pkg/workflow/web_features_worker_test.go
This change updates the web features job to use UpsertFeatureGroupLookups and stop using UpsertWebFeatureGroup and UpsertGroupDescendantInfo (those tables can be removed in the future actually.)
This is a split up of #1630
=> feat: Web Feature Job uses UpsertFeatureGroupLookups [Pt 2/3]

infra/backend/service.tf
This should give more chances for our servers to start.  We made this change after a failure to start in one region.
=> Increase failure_threshold

backend/pkg/httpserver/get_feature_test.go, backend/pkg/httpserver/get_features_test.go, lib/gcpspanner/spanneradapters/backend.go, lib/gcpspanner/spanneradapters/backend_test.go, openapi/backend/openapi.yaml
This adds support for the positive developer signals that will land in https://github.com/web-platform-dx/developer-signals
Makes the developer_signals object optional since not all features will have issues in that repository.
The database logic to get this data will happen in a future PR.
Fixes #1664
=> feat: Support developer signals in the openapi doc

infra/backend/service.tf
We should set the startup probe to the same as the otel package.
The backend container depends on the otel image to startup first. But AFAIK, the probe for the main container does not start evaluating until the sidecar (otel) container is live. But regardless, the default startup probe fails after one failure.
=> Set startup probe for backend as the same as otel

lib/gcpspanner/browser_feature_support_event.go, lib/gcpspanner/client.go, lib/gcpspanner/feature_group_lookups.go, lib/gcpspanner/web_features.go, lib/gcpspanner/wpt_run_feature_metric.go
Fixes #1697
This commit refactors the generic `entitySynchronizer` to be more robust to large cascading deletes. This is done by moving some of the cascade deletion logic into the application layer for select tables.
The previous `ON DELETE CASCADE` approach could fail with a "too many mutations" error if a single parent delete triggered a cascade of over 80,000 child record deletions. The [docs](https://cloud.google.com/spanner/docs/foreign-keys/overview#:~:text=If%20the%20number,child%20tables%20first.) say the following:
> If the number of mutations in a transaction exceeds 80,000, the transaction fails. Such large cascading deletes work well for tables with an "interleaved in parent" relationship, but not for tables with a foreign key relationship. If you have a foreign key …
=> fix: Handle large cascades by proactively deleting select child rows

GEMINI.md
Gemini Code Assist is already installed in the Devcontainer. This should help improve it.
This file was actually generated by asking the Code Assist in the vscode devcontainer to generate this.
Started off with this prompt:
```
> Do you know about GEMINI.md files?
(Answered)
> Are you able to look through my codebase and provide a GEMINI.md
```
It initially did a good job on the backend directory. But I had to prompt it to analyze the other directories.
=> Add GEMINI.md for the project

backend/cmd/server/main.go, backend/manifests/pod.yaml, backend/pkg/httpserver/create_saved_search_test.go, backend/pkg/httpserver/get_feature.go, backend/pkg/httpserver/get_feature_metadata_test.go, backend/pkg/httpserver/get_feature_test.go, backend/pkg/httpserver/get_features_test.go, backend/pkg/httpserver/get_saved_search_test.go, backend/pkg/httpserver/list_aggregated_baseline_status_counts_test.go, backend/pkg/httpserver/list_aggregated_feature_support_test.go, backend/pkg/httpserver/list_aggregated_wpt_metrics_test.go, backend/pkg/httpserver/list_chromium_usage_test.go, backend/pkg/httpserver/list_feature_wpt_metrics_test.go, backend/pkg/httpserver/list_missing_one_implementation_counts_test.go, backend/pkg/httpserver/list_missing_one_implementation_features_test.go, backend/pkg/httpserver/list_user_saved_searches_test.go, backend/pkg/httpserver/put_user_saved_search_bookmark_test.go, backend/pkg/httpserver/remove_saved_search_test.go, backend/pkg/httpserver/remove_user_saved_search_bookmark_test.go, backend/pkg/httpserver/server.go, backend/pkg/httpserver/server_test.go, backend/pkg/httpserver/update_saved_search_test.go, infra/backend/service.tf, infra/backend/variables.tf, infra/main.tf, lib/backendtypes/feature_result.go, lib/gcpspanner/spanneradapters/backend.go, lib/gcpspanner/spanneradapters/backend_test.go, openapi/backend/openapi.yaml
This commit introduces logic to handle feature evolution, where a feature can be moved (renamed) or split into multiple new features. The `/v1/features/{feature_id}` endpoint now provides specific responses to guide clients on how to handle these cases.
A `FeatureResult` visitor pattern has been implemented to differentiate between three outcomes:
-   **Regular Feature**: The endpoint returns a `200 OK` with the feature data as before.
-   **Moved Feature**: The endpoint returns a `301 Moved Permanently` redirect with a `Location` header pointing to the new feature's canonical URL.
-   **Split Feature**: The endpoint returns a `410 Gone` with a response body detailing the new features that have replaced the requested one.
To support the `301` redirect, a `BASE_URL` environment variable …
=> feat(api): Handle moved and split features in GetFeature endpoint

lib/gcpspanner/spanneradapters/backend.go, lib/gcpspanner/spanneradapters/backend_test.go
This commit updates the Spanner backend adapter to handle cases where a feature has evolved by being moved or split. The `GetFeature` function is now responsible for orchestrating the lookup logic to determine the feature's current state.
The function implements a sequential lookup process:
1.  It first attempts to fetch the feature as a standard entry.
2.  If the feature is not found (`ErrQueryReturnedNoResults`), it subsequently queries for a "moved" record associated with the feature key.
3.  If still not found, it performs a final query for a "split" record.
To communicate the result of this process, the function's signature now returns a `*backendtypes.GetFeatureResult`, which uses the visitor pattern. This allows the calling layer (the HTTP server) to cleanly handle the three …
=> feat(spanneradapters): Implement multi-step lookup for feature evolution

lib/gcpspanner/client.go, lib/gcpspanner/daily_chromium_histogram_metrics.go, lib/gcpspanner/daily_chromium_histogram_metrics_test.go, lib/gcpspanner/feature_search_test.go, lib/gcpspanner/spanneradapters/uma_metric_consumer.go, lib/gcpspanner/spanneradapters/uma_metric_consumer_test.go, lib/gcpspanner/web_features_fk_test.go, util/cmd/load_fake_data/main.go
Previously, the UMA metric consumer would only store histogram metrics that could be successfully mapped to an existing web feature ID. This meant that metrics for new or unmapped features were discarded.
This change modifies the data ingestion logic to ensure all metrics are saved:
1.  All histogram metrics for a given day are now unconditionally saved to the `DailyChromiumHistogramMetrics` table.
2.  A separate step then attempts to associate these metrics with known web features in the `FeatureChromiumHistogramMetrics` table.
3.  The `LatestFeatureChromiumHistogramMetrics` table is now updated using a synchronization operation, ensuring it accurately reflects the latest data and handles removals correctly.
This separation makes the data ingestion more robust, preventing data loss and …
=> feat(metrics): Store all UMA metrics regardless of feature mapping

lib/gh/download_file_from_release.go, lib/gh/download_file_from_release_test.go, lib/go.mod, lib/go.sum, workflows/steps/services/bcd_consumer/pkg/workflow/bcd_releases_worker.go, workflows/steps/services/bcd_consumer/pkg/workflow/bcd_releases_worker_test.go, workflows/steps/services/web_feature_consumer/cmd/job/main.go, workflows/steps/services/web_feature_consumer/pkg/workflow/web_features_worker.go, workflows/steps/services/web_feature_consumer/pkg/workflow/web_features_worker_test.go
Depends on #1745 
This commit introduces the capability to parse data files from GitHub releases based on their semantic version tag. This is crucial for handling evolving data schemas from upstream sources like `web-features`.
Key changes:
-   **`lib/gh`**: `DownloadFileFromRelease` now returns a `*gh.File` struct containing both the file contents and the release's semver tag.
-   **`web_feature_consumer`**: A new `parseByVersion` method uses the release tag to select the appropriate parser. It currently supports routing to V2 and V3 parsers for `web-features` data, ensuring backward compatibility and readiness for the new schema.
-   **`bcd_consumer`**: Updated to use the new `*gh.File` struct, though it does not yet perform version-based parsing.
-   **Testing**: New tests have been …
=> feat: Add version-based data parsing

lib/gcpspanner/spanneradapters/web_features_consumer.go, lib/gcpspanner/spanneradapters/web_features_consumer_test.go, workflows/steps/services/web_feature_consumer/pkg/workflow/web_features_worker.go, workflows/steps/services/web_feature_consumer/pkg/workflow/web_features_worker_test.go
This commit refactors the InsertWebFeatures function and its call sites to use the ProcessedWebFeaturesData struct instead of a raw map of features.
In the future, we will need this information to know which features were moved so we know how to moved data around.
=> Refactor(web_feature_consumer): Use ProcessedWebFeaturesData for insertion

frontend/src/static/js/components/webstatus-typeahead.ts
This is a port of https://github.com/GoogleChrome/chromium-dashboard/pull/5346
Thanks to @jrobbins  for this!
=> Don't automatically select 0th autocomplete candidate

infra/storage/spanner/migrations/000020.sql, lib/gcpspanner/client.go, lib/gcpspanner/moved_web_features.go, lib/gcpspanner/moved_web_features_test.go, lib/gcpspanner/split_web_features.go, lib/gcpspanner/split_web_features_test.go, lib/gcpspanner/web_features.go
This commit introduces the capability to handle web features that have been moved (renamed) or split into multiple new features. This is essential for maintaining historical data integrity and providing a seamless user experience when feature definitions evolve.
Key changes include:
- **Database Schema:**
- Adds `MovedWebFeatures` and `SplitWebFeatures` tables to the Spanner schema to track these changes.
- **DB Client:**
- Implements `SyncMovedWebFeatures` and `SyncSplitWebFeatures` to synchronize the database with the latest feature definitions from the `web-features` repository.
- Provides new data access methods (`GetMovedWebFeatureDetailsByOriginalFeatureKey`, `GetSplitWebFeatureByOriginalFeatureKey`, `GetAllMovedWebFeatures`) to query the new tables.
- Introduces a generic …
=> feat: Add support for moved and split web features

infra/storage/spanner/migrations/000021.sql, lib/gcpspanner/feature_developer_signals.go, lib/gcpspanner/feature_developer_signals_test.go
Fixes #1661
This commit introduces the infrastructure to store and manage developer signals for web features, starting with a "thumbs up" count. This provides a mechanism to gather and surface developer feedback and interest directly on web features.
Key changes include:
- **New `LatestFeatureDeveloperSignals` Table:** A new Spanner table is created with a database migration to store the thumbs up count for each feature. It is linked to the `WebFeatures` table with a cascading delete to ensure data integrity. This is to support the data from https://web-platform-dx.github.io/developer-signals/web-features-signals.json
- **Data Access Layer:** The `gcpspanner` package is extended with a `latestFeatureDeveloperSignalsMapper` that implements the `syncableEntityMapper` interface. 
- **Client …
=> feat(database): Add developer signals for web features

lib/fetchtypes/types.go, lib/gh/download_file_from_release.go, lib/httputils/fetcher.go, lib/httputils/fetcher_test.go, workflows/steps/services/chromium_histogram_enums/workflow/chromium_codesearch_enum_fetcher.go, workflows/steps/services/chromium_histogram_enums/workflow/job_processor.go, workflows/steps/services/chromium_histogram_enums/workflow/job_processor_test.go, workflows/steps/services/common/repo_downloader/pkg/gh/download.go, workflows/steps/services/uma_export/workflow/http_metrics_fetcher.go, workflows/steps/services/uma_export/workflow/http_metrics_fetcher_test.go, workflows/steps/services/wpt_consumer/pkg/workflow/http_results_getter.go, workflows/steps/services/wpt_consumer/pkg/workflow/http_results_getter_test.go
Background: I was about to add a new workflow for the developer signals and saw that I was about to write code that I already used in many places.
This commit introduces a new HTTPFetcher in lib/httputils to standardize and centralize HTTP fetching logic across the application.
The new HTTPFetcher provides a consistent way to handle HTTP requests, including support for custom headers, expected status codes, and robust error handling for cases like network errors, unexpected status codes, and missing response bodies.
The following modules have been refactored to use the new HTTPFetcher:
- lib/gh/download_file_from_release.go
- workflows/steps/services/chromium_histogram_enums/workflow/chromium_codesearch_enum_fetcher.go
- workflows/steps/services/common/repo_downloader/pkg/gh/download.go
- …
=> Refactor HTTP fetching into a common module

lib/developersignaltypes/types.go, lib/gcpspanner/spanneradapters/developer_signals_consumer.go, lib/gcpspanner/spanneradapters/developer_signals_consumer_test.go
This commit introduces the necessary components to process and store developer signals from an external workflow into the Spanner database.
It adds:
- A new `DeveloperSignalsConsumer` adapter in `spanneradapters` to handle the data transformation.
- A shared `developersignaltypes` package to define a common data structure for signals, decoupling the workflow from the Spanner storage model.
- Unit tests with a mock client to ensure the adapter correctly converts the data.
Fixes: #1783
=> feat(data): Add adapter for developer signal ingestion

lib/gcpspanner/spanneradapters/chromium_historgram_enum_consumer.go, lib/gcpspanner/spanneradapters/chromium_historgram_enum_consumer_test.go, lib/gcpspanner/spanneradapters/developer_signals_consumer.go, lib/gcpspanner/spanneradapters/developer_signals_consumer_test.go, lib/gcpspanner/spanneradapters/migration.go, lib/gcpspanner/spanneradapters/migration_test.go
Introduces a new generic `Migrator` in `lib/gcpspanner/spanneradapters` to handle data migration when a web feature key is renamed or moved. This centralizes the logic for checking conflicts and applying updates when a feature ID changes in an upstream data source.
The previous implementation had duplicated and specific logic within each data consumer (`ChromiumHistogramEnumConsumer` and `DeveloperSignalsConsumer`) to handle these migrations. This new approach provides a single, reusable, and testable component for this task.
This commit refactors the following consumers to use the new `Migrator`:
- `ChromiumHistogramEnumConsumer`: The existing migration logic is replaced with the new migrator.
- TODO for later: I need to fix the name of the file.
- `DeveloperSignalsConsumer`: Migration …
=> Introduce generic migrator for feature key renames & add use it for dev signals

package-lock.json, package.json
A vulnerability in the `tmp` package (GHSA-52f5-9888-hmc6) was detected by `npm audit`. This change introduces an override in `package.json` to force the use of the patched version `0.2.4`, as a direct update is not possible through the dependency chain.
This resolves the vulnerability without requiring any code changes.
This was created because dependabot kept failing to create a patch to fix this.
=> chore(deps): override tmp to patch vulnerability

GEMINI.md
Updates the Gemini assistant's knowledge base (`GEMINI.md`) based on an analysis of recent commits. This captures significant architectural and feature changes, including:
- **Developer Signals:** Documents the new `developer_signals_consumer` workflow, the `LatestFeatureDeveloperSignals` database table, and the associated data adapters and types.
- **Feature Evolution:** Explains how the system now handles "moved" and "split" features, including the new `MovedWebFeatures` and `SplitWebFeatures` tables.
- **Data Migration:** Details the new pre-delete hook (`GetChildDeleteKeyMutations`) for handling large cascade deletes in Spanner and the generic data migrator for feature key renames.
- **Code Refactoring:** Notes the refactoring of HTTP fetching into a common `fetchtypes` module and the …
=> docs(gemini): Update knowledge base and maintenance instructions

frontend/src/static/js/components/test/webstatus-feature-page.test.ts, frontend/src/static/js/components/webstatus-feature-page.ts
The previous logic did not render the developer signal component if the number of upvotes was zero, because it was treated as a falsy value.
This change corrects the condition to explicitly check for `undefined` instead, allowing the component to be rendered correctly when there are zero upvotes.
A new unit test is added to verify this behavior.
=> fix(frontend): Display developer signals with zero upvotes
