GoogleChrome/webstatus.dev

DEPLOYMENT.md
DEVELOPMENT.md
README.md

Moves part of the DEVELOPMENT readme to a new DEPLOYMENT readme.
Add more sections to the README.md

Add more docs

---

infra/ingestion/workflows/web_features_repo/variables.tf
infra/ingestion/workflows/wpt/wpt_job.tf

- Increases the timeout for the web features workflow
- Increases the CPU and memory for the wpt workflow
Refer to #287 for more information
Fixes #287

Increase workflow timing and resources

---

backend/cmd/server/main.go

Include http://* for local environment testing.

---

.github/workflows/ci.yml
.github/workflows/devcontainer.yml

More information:
- https://github.com/orgs/community/discussions/27086
Fixes https://github.com/GoogleChrome/webstatus.dev/actions/runs/9539838904/job/26290684622
```
[2024-06-17T00:04:28.261Z] ERROR: invalid tag "ghcr.io/GoogleChrome/webstatus-dev-devcontainer:latest": repository name must be lowercase
```

Fix capitalization error for docker image package

---

.github/dependabot.yml

This change adds dependabot for the repository for the various package managers

chore: enable dependabot for the repository

---

workflows/steps/services/web_feature_consumer/pkg/data/parser.go
workflows/steps/services/web_feature_consumer/pkg/data/parser_test.go

After talking with @foolip, we need to remove the range character "≤" from some of the fields. [Example](https://github.com/web-platform-dx/web-features/blob/1592776125c017ac0daffaf09924c327fbc18beb/features/pre.yml.dist#L14)
This post process step rebuilds each of the structs. We do this so that go-exhaustruct will let us know if any new fields are added. And at that time we can look how to handle it.
The alternative would be to have conditionals for the specific fields that we know of. But during regeneration, we would not get alerted if a new field was added.

Add post process step to the web features parsing

---

frontend/package.json
package-lock.json

The first step [1] of Google Cloud Identity Platform is to install the firebase package.
This change only does that. Future changes will use it. Installing the package, adds a lot of lines to the package lock file. So I figured I would make a PR just for this.
[1] https://cloud.google.com/identity-platform/docs/sign-in-user-email#sign_in_the_user

Install firebase package

---

lib/gcpspanner/feature_base_query.go
lib/gcpspanner/feature_search_query.go

Upon deploying the changes to staging, the site stopped working.
This is because the spanner emulator != the GCP spanner exactly.
The errors can be found at #576
Fixes #576

Fix query problems from #568

---

lib/gcpspanner/spanneradapters/web_feature_groups_consumer.go
lib/gcpspanner/spanneradapters/web_feature_groups_consumer_test.go
workflows/steps/services/web_feature_consumer/cmd/server/main.go
workflows/steps/services/web_feature_consumer/pkg/httpserver/server.go
workflows/steps/services/web_feature_consumer/pkg/httpserver/server_test.go

Depends on #594 
**Description:**
This PR introduces the `WebFeatureGroupConsumer` to process and store group-related data from the WebDX web features repository. It builds upon the previously added `WebDXGroups` and `WebFeatureGroups` tables to establish relationships between web features and their associated groups.
**Key Functionality**
* **Group Hierarchy Construction:** The consumer builds an in-memory representation of the group hierarchy based on the `parent` relationships in the input data.
* **Descendant Calculation:** It efficiently calculates and populates the `DescendantGroupIDs` field for each group, optimizing future queries for features associated with a group and its descendants.
* **Feature-Group Mapping:** It establishes the connections between web features and their …

[2/4] Implement Web Feature Groups Consumer

---

util/cmd/load_fake_data/main.go

Depends on #596 
While developers could use dev_workflows to get real groups from the web features repo, it takes awhile.
This allows developers to have their environment come with three groups:
- parent1
- parent2
- child3
Searching for parent1 should also include the features in child3.

[4/4] Add fake groups to dev fake data

---

util/cmd/load_fake_data/main.go

Depends on #602 
While developers could use dev_workflows to get real snapshots from the web features repo, it takes awhile.
This allows developers to have their environment come with three snapshots:
- parent1
- parent2

[5/5] Add fake snapshots to dev fake data

---

frontend/src/static/js/components/webstatus-overview-filters.ts

Add autocomplete vocabulary items for group:, snapshot:, and revised available_date:

---

lib/gcpspanner/client.go
lib/gcpspanner/wpt_run.go

Currently, we have generic methods for writing rows to the spanner database but not for reading. This adds a new entityReader type. Additionally, since some of the writers already do reading, I made the writers inherit from this new reader.
This PR also makes wpt_runs use the new entityReader.
Future PRs will also use this as part of the split up of #616.

refactor: Add generic entity reader

---

Makefile
workflows/steps/services/chromium_histogram_enums/cmd/job/main.go
workflows/steps/services/chromium_histogram_enums/go.mod
workflows/steps/services/uma_export/cmd/job/main.go
workflows/steps/services/uma_export/go.mod

This introduces the high level go modules to the go workspace for the two new process. One will be to read the enums from the chromium histogram file. The other will query data from the uma export server.
More about multi-module workspace in Go can be found here: https://go.dev/doc/tutorial/workspaces
We do this already for other Go processes.
Part of splitting up #616 
Parent PR: #668

Add Go modules for uma and chromium processes

---

lib/workerpool/pool.go
lib/workerpool/pool_test.go
workflows/steps/services/bcd_consumer/cmd/job/main.go
workflows/steps/services/bcd_consumer/pkg/workflow/bcd_releases_worker.go
workflows/steps/services/bcd_consumer/pkg/workflow/bcd_releases_worker_test.go
workflows/steps/services/wpt_consumer/cmd/job/main.go
workflows/steps/services/wpt_consumer/pkg/workflow/wpt_runs_worker.go
workflows/steps/services/wpt_consumer/pkg/workflow/wpt_runs_worker_test.go

Previously, each process had to create their own channel and send the jobs into the channel before starting the workerpool. This led to some near duplicate code for each process. In anticipation of two new processes (1. Chromium Enum & 2. UMA Export), I refactored the workerpool logic to include the creation of the job channel and feeding the jobs into that channel.
This change helps out with the two existing processes (BCD and WPT) also.
This removes the need for each process to define a Worker struct (with the nearly duplicate code) and instead rely on the process specific Processor.

Refactor: Centralize worker start logic

---

backend/pkg/httpserver/get_saved_search.go
backend/pkg/httpserver/list_saved_searches.go
openapi/backend/openapi.yaml

- Get a single saved search
- List saved searches
For now, it returns hard coded values to help with UI building

Start of the saved searches API design.

---

otel/Dockerfile

as title, this should fix the https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35138

Update otel/opentelemetry-collector-contrib to 0.110.0

---

.github/ISSUE_TEMPLATE/incorrect_data.md

This commit introduces a new issue template to help users determine if a perceived data discrepancy originates from our webapp or the upstream data sources we ingest.
The template guides users to:
- Identify the source of the data in question.
- Compare the data displayed on our webapp with the original source.
- If the data is the same: Directs them to the appropriate upstream repository to report the issue.
- If the data is different: Prompts them to provide specific details and context to help us investigate and fix the problem.

Add issue template to guide users on data discrepancies

---

lib/gcpspanner/client.go
lib/gcpspanner/user_search_bookmarks.go
lib/gcpspanner/user_search_bookmarks_test.go

For now: since all the searches are public, we don't do any access checking.

Add database methods to add and remove bookmarks

---

openapi/backend/openapi.yaml

Fixes #780
Modifies the schema to accommodate usage data for multiple browsers, with Chromium data to start.

Modify YAML to support snapshot usage data

---

lib/gcpspanner/feature_search_query.go

Remove nolint after #915

---

lib/gcpspanner/feature_search_query.go
lib/gcpspanner/feature_search_test.go
lib/gcpspanner/spanneradapters/backend.go
openapi/backend/openapi.yaml

Add sorting for Chromium Usage

---

frontend/src/static/js/components/webstatus-overview-content.ts
frontend/src/static/js/utils/constants.ts

Address https://github.com/GoogleChrome/webstatus.dev/pull/931#issuecomment-2518788179.
- Remove the URL link
- Use a darker font
- Add content padding for description

Address bookmark UI nits

---

backend/cmd/server/main.go
backend/go.mod
backend/go.sum
backend/manifests/pod.yaml
backend/pkg/httpserver/middlewares.go
backend/pkg/httpserver/middlewares_test.go
backend/pkg/httpserver/server.go
backend/pkg/httpserver/server_test.go
e2e/tests/feature-page.spec.ts
infra/backend/service.tf
infra/backend/variables.tf
infra/main.tf

This PR improves the handling of middleware in the backend service and adds authentication using the new Bearer token middleware.
**Background**
Previously, all middleware was applied before request validation, which prevented the authentication middleware from accessing information set during validation (e.g., `BearerAuthScopes`). To address this, the OpenAPI generator provides a hook for applying middleware *after* request validation.
**Changes**
* **Middleware categorization:**
* The existing cache middleware and the new authentication middleware are moved to the post-request validation category.
* CORS and OpenTelemetry middlewares remain as pre-request validation middlewares.
* **Wrapper methods:**  Added wrapper methods to adapt standard middleware signatures to the OpenAPI …

feat: Enhance middleware handling and add authentication [4/4]

---

frontend/src/static/js/api/client.ts
frontend/src/static/js/components/test/test-helpers.test.ts
frontend/src/static/js/components/test/webstatus-line-chart-panel.test.ts
frontend/src/static/js/components/webstatus-line-chart-panel.ts

This PR introduces a new abstract class, `WebstatusLineChartPanel`, to provide a common base for creating line chart panels in the web status dashboard. This refactor aims to:
- **DRY:** Eliminate code duplication across different chart panels by centralizing common logic and structure.
- **Improve organization:** Separate page-specific code from chart-related code, making the codebase easier to understand and maintain.
- **Enhance consistency:** Ensure consistent behavior and styling across all line chart panels.
The `WebstatusLineChartPanel` class handles:
- Data processing and formatting for `webstatus-gchart`.
- Chart rendering with loading states (initial, pending, error, complete).
- Basic layout and styling using Shoelace components.
Subclasses can focus on:
- Fetching data from …

Introduce `WebstatusLineChartPanel` abstract class

---

backend/pkg/httpserver/list_aggregated_feature_support.go
backend/pkg/httpserver/list_aggregated_feature_support_test.go

This pull request implements caching for the ListAggregatedFeatureSupport API handler

Implement Caching for ListAggregatedFeatureSupport

---

backend/pkg/httpserver/get_feature.go
backend/pkg/httpserver/get_feature_test.go

This pull request implements caching for the GetFeature API handler

Implement Caching for GetFeature

---

backend/pkg/httpserver/list_chromium_usage.go
backend/pkg/httpserver/list_chromium_usage_test.go

This pull request implements caching for the ListChromiumDailyUsageStats API handler

Implement Caching for ListChromiumDailyUsageStats

---

backend/pkg/httpserver/get_features.go
backend/pkg/httpserver/get_features_test.go

This pull request implements caching for the ListFeatures API handler

Implement Caching for ListFeatures

---

backend/pkg/httpserver/list_feature_wpt_metrics.go
backend/pkg/httpserver/list_feature_wpt_metrics_test.go

This pull request implements caching for the ListFeatureWPTMetrics API handler

Implement Caching for ListFeatureWPTMetrics

---

backend/pkg/httpserver/list_missing_one_implementation_features.go
backend/pkg/httpserver/list_missing_one_implementation_features_test.go
backend/pkg/httpserver/server_test.go
openapi/backend/openapi.yaml

#1110. Create the OpenAPI documentation for MissingOneImplementationFeatures and endpoint signatures.

Create a MissingOneImplementationFeatures endpoint

---

lib/gcpspanner/spanneradapters/backend.go
lib/gcpspanner/spanneradapters/backend_test.go

This will be used by the [listUserSavedSearches](https://github.com/GoogleChrome/webstatus.dev/blob/078beb7fecb7c22cdd3eb2dbd3c814eb2e84beb9/openapi/backend/openapi.yaml#L564-L567) http handler
This is the layer between the httpserver and spanner.
It parses out the error if it is:
- A bad page token, or
- General error
This builds on #1292 and will be used by the `/v1/users/me/saved-searches` (listUserSavedSearches) endpoint

Add adapter logic for listUserSavedSearches

---

DEVELOPMENT.md
Makefile
docs/testing.md
lib/gcpspanner/create_user_saved_search.go
util/cmd/load_fake_data/main.go
util/go.mod
util/go.sum

This change adds fake users before adding the fake data.
This is necessary so that we can associate the fake searches to a user.
This change also adds a few helpers

Populate fake users before data; add fake searches

---

frontend/src/static/js/components/webstatus-overview-page.ts
frontend/src/static/js/services/test/webstatus-bookmarks-service.test.ts
frontend/src/static/js/services/webstatus-bookmarks-service.ts

Part of the split up of #1364 
This adds event listeners for the following events:
- saved-search-saved
- saved-search-edited
- saved-search-deleted
- saved-search-bookmarked
- saved-search-unbookmarked
Future PR(s) will emit those events. We create the event listeners so that anywhere in the app can emit an event and the appBookmarkInfo will update. And as a result, all the subscribers to appBookmarkInfo will get the new state automatically.
saved-search-bookmarked can use the same event listener method as saved-search-saved because:
1. The saved search owner can't toggle its bookmark status (like in  issue tracker).
2. As a result of point number 1, non owners can be the only users toggling. Which means it can use `handleSavedSearchSaved` since it just adds the saved search to the …

feature: Add event handlers for saved search and bookmark actions

---

frontend/src/static/js/components/webstatus-overview-cells.ts
frontend/src/static/js/components/webstatus-overview-table.ts

Add survey result labels to overview page

---

frontend/src/static/js/components/webstatus-feature-badge.ts

Remove unnecessary log statement

---

frontend/src/static/js/utils/constants.ts

Add missing browsers to frontend autocomplete
